### ISSUE TITLE
lp__ should be removed from deprecated features in reference manual

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/docs#10]
#### Summary:
Currently, lp__ still appears in the reference manual as being deprecated. However, it has already been removed from the language.

#### Description:
lp__ should be removed from the deprecated features list in the reference manual.

#### Additional Information:
-

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
Thanks.  I would've swore it was still available as a value, just not to set.

**Comment by mcol** [comment]
This can be closed.
