### ISSUE TITLE
Website pdf Documentation Link Broken

### ISSUE THREAD

**Issue by jmh530** [stan-dev/docs#102]
#### Summary:
The links to the documentation pdf's on the website are broken.

#### Description:
I went to the  [documentation site](https://mc-stan.org/users/documentation/) and tried to grab the latest pdf's of the documentation, available [here](https://mc-stan.org/docs/2_21/stan-users-guide-2_21.pdf), [here](https://mc-stan.org/docs/2_21/reference-manual-2_21.pdf), and [here](https://mc-stan.org/docs/2_21/functions-reference-2_21.pdf) and got 404 page not found for all of them. 

I wasn't not sure if this was the right place to report this or not.

Edit: there is no issue when I change the 2_21's in the links above to 2_20.

**Comment by jgabry** [comment]
That’s not good, thanks for reporting this!!! The links are broken for me too. @mitzimorris any chance you have time to take a peek at this? I can’t quite figure out why the pdf for 2.21 is missing but maybe I’m overlooking something that will be obvious to you!

**Comment by mitzimorris** [comment]
thanks for reporting - it was a gitignore problem - hope this fixes the problem permanently!

**Comment by jgabry** [comment]
Thanks @mitzimorris for fixing! the links seem to be working again after https://github.com/stan-dev/docs/commit/94b0fb364b9e30d8746a634f0ea2494e003f7d84 and https://github.com/stan-dev/docs/commit/d710f32d04a4a070b8275255b56eddb96fdc4f6a. 

And thanks again @jmh530 for bringing this to our attention!
