### ISSUE TITLE
Refer to "Vector, Matrix, and Array Expressions" in "Vector and Matrix Data Types" and "Array Data Types"

### ISSUE THREAD

**Issue by avehtari** [stan-dev/docs#107]
Based on my and my students experiences, when searching how to declare vector, matrix or array with some initial values (declaration and assignment in the same line), it is easy to find Chapter "5 Data Types and Declarations" in the reference manual, but sections "5.4 Vector and Matrix Data Types" and "5.5 Array Data Types" tell only how to declare these, but not how to assign initial values. The needed information is in the section "6.3 Vector, Matrix, and Array Expressions", but it is difficult to find that as the chapter is named just "Expressions" and making the connection is not easy.

- [ ] Add to sections 5.4 and 5.5 a reference to section 6.3 so that it is easier to find the related content.

#### Current Version:
Stan Reference Manual
Version 2.21

**Comment by bob-carpenter** [comment]
Good catch---there's probably a lot of this in the user's guide because it evolved over time.  The array and matrix construction expressions are much newer than the data types.
