### ISSUE TITLE
add floating point issues with constraints to manual and user's guide

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/docs#110]
#### Summary:

There are situations where our floating point operations have one behavior mathematically and another with floating point rounding, underflow, or overflow.  We should document what this does and how to fix or trap the issue in simple cases.   

For example, with a parameter declared with `real<lower = 0> sigma`, if the unconstrained value is high magnitude and negative (e.g., -500), then the constrained value will be 0 because `exp(-500)` underflows to 0.

Similarly, with `real<lower = 0, upper = 1>`, we'll get rounding to 1 for large-ish values of the parameter, even though mathematically, inverse logit should be strictly in (0, 1) (exclusive bounds).

See [Aki's comment](https://github.com/stan-dev/math/issues/1441#issuecomment-562855190) on the stan-dev/math issue for lub_constrain for more discussion.

#### Current Version:
v2.18.0

**Comment by avehtari** [comment]
@bob-carpenter can this be closed with #786 or would you like more somewhere else in the doc?
