### ISSUE TITLE
stan-manuals.sty seems to be unused

### ISSUE THREAD

**Issue by mcol** [stan-dev/docs#115]
#### Summary:
File `src/stan-users-guide/stan-manuals.sty` doesn't seem to be referenced from anywhere. It contains a number of `newcommand` statements to help format acronyms or symbols, none of which seems to be used either. So, unless there's a plan to start using it, we could just remove it. I tried locally and the users guide compiled fine, and on a quick inspection nothing seemed broken.

**Comment by mitzimorris** [comment]
> I tried locally and the users guide compiled fine

you checked the pdfs?
I will check this out locally too - I think you're probably right.

**Comment by bob-carpenter** [comment]
It was the style for the docs before they moved to markdown.  It's probably still being used for the CmdStan docs, but that's a different repo.

**Comment by mitzimorris** [comment]
> It's probably still being used for the CmdStan docs, but that's a different repo.

CmdStan docs contains its own copy - https://github.com/stan-dev/cmdstan/blob/develop/src/docs/cmdstan-guide/stan-manuals.sty

**Comment by mitzimorris** [comment]
did the cleanup -  https://github.com/stan-dev/docs/commit/9437b5cf0d064c030c612d8e03a519434d0197d1
