### ISSUE TITLE
Add add_diag to documentation

### ISSUE THREAD

**Issue by avehtari** [stan-dev/docs#117]
#### Summary:

Add `add_diag` to the documentation. Maybe in section "5.8 Diagonal Matrix Functions"

`add_diag` was added to the language in Jul 30 2019 in (stan-dev/stan#2779 and stan-dev/math#871) and is thus included in Stan v2.21.0 (18 October 2019). 

Supported signatures:

matrix add_diag(matrix m, row_vector d)
matrix add_diag(matrix m, vector d)
matrix add_diag(matrix m, real d)

Description:
Add `d` to the diagonal of matrix `m`. If `d` is scalar, it is added to the every diagonal element of `m`.

**Comment by mitzimorris** [comment]
fixed via https://github.com/stan-dev/docs/commit/a80428c3f1ad40b94d75a26e41f8191dc463162a

**Comment by mitzimorris** [comment]
regenerated 2_21 docs via b6144bce52a0d5c281a64a865891fc5c966a024a
