### ISSUE TITLE
Wiener function docs not rendering properly

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/docs#118]
#### Summary:
The constraints for the wiener lpdf are not rendering properly:

https://mc-stan.org/docs/2_21/functions-reference/wiener-first-passage-time-distribution.html

Also the boundaries at the bottom have some stuff in there that doesn't look right.

#### Current Version:
v2.21.0

**Comment by mitzimorris** [comment]
rendering problem?  not on my machine:

<img width="740" alt="Untitled" src="https://user-images.githubusercontent.com/5466612/72185536-0394a780-33c1-11ea-8666-eb7f1d745ae6.png">

**Comment by SteveBronder** [comment]
@bbbales2 are you using firefox? It rendered for me but took a while on firefox. It could be weird mix of Ad Blocker / Mathjax

Ran fine on chrome

![Screenshot from 2020-01-10 16-07-27](https://user-images.githubusercontent.com/5857231/72186500-6c7d1f00-33c3-11ea-8ece-94906fbb0b51.png)

**Comment by bbbales2** [comment]
Chromium in Ubuntu 18.04. Weirdly enough Firefox works fine for me :/. I didn't check this -- good call.

I guess this is probably something we have no control over and we just hope it goes away with updates.
