### ISSUE TITLE
positive vs nonnegative continuous distribution confusion

### ISSUE THREAD

**Issue by nhuurre** [stan-dev/docs#121]
#### Summary:
Section 17 "Non-negative Continuous Distributions" is redundant. Remove it and move the two distributions elsewhere.

#### Description:
The functions reference makes a distinction between "positive continuous distributions" (section 16)
and "nonnegative continuous distributions" (section 17). This makes no sense because the claimed supports differ only by one point, namely zero, but individual points have vanishing probability when the distribution is continuous.

These aren't about "zero-avoiding" distributions either. The exponential distribution has nonzero density near zero but is listed as a "positive distribution".
Also recall that the square root of an exponentially distributed variate follows Rayleigh distribution. Square root maps positive values to positive values, and in fact moves near-zero values away from zero. And yet, Rayleigh appears under "non-negative distributions".

Beside Rayleigh, the only other "non-negative continuous" distribution in the reference is Wiener First Passage Time distribution. The definition indicates that the Wiener distribution is lower-bounded by input parameter `tau` and therefore it actually belongs in the positive _lower-bounded_ distributions section.

**Comment by bob-carpenter** [comment]
This whole issue is confusing and should be clarified in the doc.  Moving these distributions is fine.  The Pareto is another lower-bounded distribution.

We struggled dealing with distributions where some of the boundary conditions make sense.  For instance, normal(mu, 0) might be interpreted as a point mass at 0.  We then tried to fudge some of the definitions to make them work that way.  In retrospect, that was a terrible idea and we should just throw exceptions outside of acceptable boundaries.

There have also been some fixes lately to some early mistakes like hard-bounding minimum returns, which wound up leading to non-monotonic (and non-differentiable) behavior.

**Comment by mcol** [comment]
What could be a good chapter title to encompass all of these? Would "Lower bounded distributions" work?

**Comment by nhuurre** [comment]
Rayleigh distribution goes in section 16 Positive Continuous Distributions (because its lower bound is always zero, and it is in fact a special case of the Chi distribution) and Wiener First Passage Time distribution goes in section 18 Positive Lower-Bounded Probabilities (strangely the only distribution list that does not have the word "distributions" in the title)

**Comment by bob-carpenter** [comment]
Things drift over time.  The Pareto is the one where you specify a parameter that's the lower bound.  So it should go in positive lower-bounded.  Uniform is the other one that's lower bounded, but it's also upper bounded.
