### ISSUE TITLE
No index page at mc-stan.org/docs

### ISSUE THREAD

**Issue by seantalts** [stan-dev/docs#14]
#### Summary:
Accessing https://mc-stan.org/docs gives me a 404 (though now I know I can go to https://mc-stan.org/docs/2_18/reference-manual/index.html

#### Current Version:
v2.18.0

**Comment by mitzimorris** [comment]
trying to address:  https://github.com/stan-dev/docs/issues/5

> The other solution, which I like even better, is to move the directory into the actual web site directory and only serve the actual manuals from this site. It may not work as there may be an assumption that there's an index here. If so, you'll have to use your judgement and doc around possible confusions.

agreed, 404 is bad.
I will put back the index page as it was, and add method to the build script to regenerate the index page as needed.

**Comment by WardBrian** [comment]
Closed by #409
