### ISSUE TITLE
clarify elementwise quotient doc in functions reference

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/docs#142]
#### Summary:

@JohannesBuchner commented [here on an old PR for Stan](https://github.com/stan-dev/stan/pull/660#issuecomment-580340759):

> elementwise quotient of \farg{y} and \farg{x}}" -- since this is somewhat ambiguous, could you please add in the documentation that this means y/x (which I find unintuitive).

Add clarification to doc.

**Comment by JohannesBuchner** [comment]
Could you confirm to me whether it is really true that in Stan

`` a = b ./ c ``

means

`` a[i] = c[i] / b[i] ``

for each ith element of vectors a, b and c?

**Comment by bob-carpenter** [comment]
Yes.  It follows MATLAB conventions for elementwise operations.
It seems there's a hole in our doc:

https://mc-stan.org/docs/2_22/functions-reference/elementwise-functions.html

I'm creating an issue for that.

**Comment by rok-cesnovar** [comment]
Duplicate of #149
