### ISSUE TITLE
Update list of reserved keywords

### ISSUE THREAD

**Issue by mcol** [stan-dev/docs#145]
#### Summary:
Given the switch to stanc3, there are a few more keywords that should be listed as reserved (see https://discourse.mc-stan.org/t/list-of-stanc3-new-reserved-keywords/12948/5). The relevant file is `src/reference-manual/expressions.Rmd`.

#### Additional Information:
Should ideally be done before publishing docs for 2.22.

**Comment by avehtari** [comment]
It might be good to also to mention which keywords were added in 2.22
