### ISSUE TITLE
missing function doc for elementwise operations .* and ./

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/docs#149]
#### Summary:

The [current documentation for elementwise functions](https://mc-stan.org/docs/2_22/functions-reference/elementwise-functions.html) is empty.  It should document `operator.*` and `operator./`.  

They show up in [another section](https://mc-stan.org/docs/2_22/functions-reference/matrix-arithmetic-operators.html).

#### Current Version:
v2.18.0

**Comment by rok-cesnovar** [comment]
Fixed by https://github.com/stan-dev/docs/pull/306
