### ISSUE TITLE
Footnotes are broken on the html site

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/docs#150]
#### Summary:

Some of the footnotes are missing from the html site. Footnotes on pdf are working as intended.

#### Problem:

There are 3 footnotes fn25, fn26, fn27 but only fn25 is shown on the following page

https://mc-stan.org/docs/2_22/reference-manual/notation-for-samples-chains-and-draws.html

This link works:
https://mc-stan.org/docs/2_22/reference-manual/notation-for-samples-chains-and-draws.html#fn25

But this does not:
https://mc-stan.org/docs/2_22/reference-manual/notation-for-samples-chains-and-draws.html#fn27

The same footnote on pdf is fine:

See page 150 (number on the corner)
`Split R-hat for Detecting Non-Stationarity`--> 

There is a footnote for `lp__` and the link in the text is linked to the footnote.

https://mc-stan.org/docs/2_22/reference-manual-2_22.pdf

#### Current Version:
v2.22.0

**Comment by bob-carpenter** [comment]
I noticed that in something I'm doing and wound up pulling things out of footnotes.  But if anyone knows how to fix this more generally so that footnotes work, it'd be a huge help.  I didn't see anything weird about the placement or content of footnotes I was trying in another branch that didn't work.

**Comment by ahartikainen** [comment]
Is this bug related? That footnote is multiline.

https://github.com/rstudio/bookdown/issues/840

**Comment by bob-carpenter** [comment]
Sure sounds related.  Let's just move to making footnotes single line.  I wasn't getting this with tufte format on my own docs, but it looks like these more basic formats are problematic.

**Comment by cderv** [comment]
Just to let you know I have made a PR that you could test so that multiline footnotes work again. 
See https://github.com/rstudio/bookdown/pull/876

**Comment by bob-carpenter** [comment]
That's awesome, @cderv.  Thanks for letting us know.
