### ISSUE TITLE
Weird formatting in html

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/docs#152]
#### Summary:
Please provide a short couple sentence summary.

Weird formatting for { and }

#### Description:
Describe the issue as clearly as possible.

in https://github.com/stan-dev/docs/blob/814de1355c2961f8363ee86937da27294d370304/src/reference-manual/statements.Rmd

```
The open curly bracket (`\{`) is the first character of the block
--
991 | and the close curly bracket (`\`}) is the last character.
```

and then in html https://github.com/stan-dev/docs/blob/23ec2e4be42933fcac6b3776f6f46917a54ea2e8/docs/2_22/reference-manual/statement-blocks-and-local-variable-declarations.html

```
<p>The open curly bracket (<code>\{</code>) is the first character of the block
--
657 | and the close curly bracket (<code>\</code>}) is the last character.</p>
```
#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.22.0

**Comment by bob-carpenter** [comment]
I don't think this is a markdown bug, it just looks like someone (probably me) confused whether they were in an HTML or a LaTeX environment.  These should just look like

```
(`}`)
```

in the .Rmd file.
