### ISSUE TITLE
Fix capitalization in titles

### ISSUE THREAD

**Issue by mcol** [stan-dev/docs#154]
#### Summary:
This is the rule @bob-carpenter suggested in https://github.com/stan-dev/docs/pull/148#discussion_r383437917:

*  `# XXX` uses title punctuation for XXX (all caps other than "function" words [prepositions, determiners, auxliary verbs, other particles, etc.])

*  `## XXX` should use sentence punctuation for XXX (initial caps, not all caps)

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
If we wanted to follow the example of @andrewgelman's books, everything would be in sentence punctuation.  But that's one step too far for me.
