### ISSUE TITLE
Possible typo in functions reference for lognormal

### ISSUE THREAD

**Issue by nesanders** [stan-dev/docs#159]
#### Summary:
I think the mathematical definition of the lognormal in the functions reference document Section 16.1 may have a typo.

#### Description:

Here's a screenshot from version 2_22 of the functions reference doc:
![Screenshot_20200317_171510](https://user-images.githubusercontent.com/1727426/76902663-e1148400-6872-11ea-85ea-bf14dd14b820.png)

Based on the function definition [here](https://mc-stan.org/math/dc/d27/lognormal__lpdf_8hpp_source.html), I think the actual formula is,

$\rm{LogNormal} = \frac{1}{\sqrt{2\pi|\sigma}\frac{1}{(y-mu)}\exp\left(-\frac{1}{2}\left(\frac{\log(y-\mu)}{\sigma}\right)^2\right)$

Note the \mu parameter is inside the log within the exponential and is also part of the normalization.

#### Current Version:
v2.22.0

**Comment by bob-carpenter** [comment]
What's in the doc is right.  See https://en.wikipedia.org/wiki/Log-normal_distribution.  It's just `y` instead of `y - mu` in the denominator out front.  So I'm going to close this.

Is there a piece of the implementation you think doesn't match that?  Line 113 has the correct denominator in the implementation.

**Comment by nesanders** [comment]
Thank you for taking a look, Bob, and sorry for my confusion!  It stemmed from 1) the implementation code seeming to carry around the (y-mu) term ("logy_m_mu") and 2) the definition from the [scipy package](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.lognorm.html) being written out slightly differently.  In particular, as is indicated in the scipy docs, the stan mu parameter needs to be input to the scipy function as scale=exp(mu) to make them match.  

I'm going to go ahead and close this as a non-issue.  I know it's not unusual for the scipy and stan paramaterizations to differ slightly and I'm sure there are good efficiency reasons for the stan code to be written the way it is!  I did some systematic sampling tests between the scipy and stan versions to convince myself that they are in fact the same.  Thanks again for pointing me in the right direction.

**Comment by bob-carpenter** [comment]
> the stan mu parameter needs to be input to the scipy function as scale=exp(mu) to make them match.

I was just trying to resolve confusion about that very point earlier this week for one of our case studies.  Lognormal's hard because it's change of scale (log/linear) with a change of variables.  I can't even keep signs straight or which way around transforms are going in Jacobians.
