### ISSUE TITLE
Missing plot in ODE section of user's guide

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/docs#160]
#### Summary:
The plot should be here: https://mc-stan.org/docs/2_22/stan-users-guide/measurement-error-models.html

#### Description:
Here's some R code that should produce a plot near what I think this was meant be:

```
library(tidyverse)
library(ggplot2)
library(deSolve)

f = function(t, y, parms) {
  return(list(c(y[2], -y[1] - 0.15 * y[2])))
}

out = ode(c(y0 = 1.0, y1 = 0.0), seq(1.0, 10.0, length = 10), f) %>%
  as_tibble() %>%
  gather(state, y, y0, y1) %>%
  mutate(y_noise = rnorm(length(y), y, 0.1))

out_highres = ode(c(y0 = 1.0, y1 = 0.0), seq(1.0, 10.0, length = 1000), f) %>%
  as_tibble() %>%
  gather(state, y, y0, y1)

out %>%
  ggplot(aes(time, y_noise)) +
  geom_point(aes(color = state)) +
  geom_path(data = out_highres, aes(time, y, group = state, color = state),
            linetype = "dashed")
```

Presumably it'll need formatted to be like other plots in the manual.

(edit: added missing libraries)

#### Current Version:
v2.22.0

**Comment by torkar** [comment]
@bbbales2 , I'm not 100% sure but I think I fixed this on GitHub last week. Can you check?
