### ISSUE TITLE
transpose in use of categorical_logit w/o introduction

### ISSUE THREAD

**Issue by torkar** [stan-dev/docs#167]
In Sect. 1.6 of the User's Guide we use the transpose function on a matrix `x_beta[n]`,
```stan
y[n] ~ categorical_logit(x_beta[n]');
```
This can potentially be very confusing to a reader since they have not (AFAICT) seen `'` used in any examples before this. I suggest to either use i)

```stan 
y[n] ~ categorical(softmax(x[n] * beta));
``` 
or explain the transpose in more detail.

**Comment by bob-carpenter** [comment]
I would suggest keeping the original form and explaining that

* the apostrohe (`'`) means transpose,
* `categorical_logit` does the softmax, and
*  `x_beta[n]` is just `x * beta[n]`.

That way we don't have to sacrifice idiomatic and efficient models.

**Comment by andrewgelman** [comment]
I agree.

**Comment by rok-cesnovar** [comment]
Fixed by https://github.com/stan-dev/docs/pull/306
