### ISSUE TITLE
citation listed twice

### ISSUE THREAD

**Issue by torkar** [stan-dev/docs#169]
#### Summary:
Citation listed twice in Sect. 2.5.
#### Description:
In Sect 2.5 (User's Guide) the citation `[@Hoffman-Gelman:2011; @Hoffman-Gelman:2014]` for some reason lists `@Hoffman-Gelman:2011` twice in `References` (HTML). I've tried to fix this but failed :)
#### Current Version:
v2.22.0

**Comment by bob-carpenter** [comment]
Thanks for leaving an issue.  Did you make sure they were different references in the bibtex/all.bib file?  There might be duplicates with different (erroneous) identifiers.

**Comment by torkar** [comment]
Aah, you're completely right, Bob. The 2011 points to ArXiv and the 2014 points to the JMLR publication. So, remove the 2011 entry?

**Comment by bob-carpenter** [comment]
Before removing it, please make sure it's not being used by any of the other docs in the repo.  It's OK to replace it in other docs, too.
