### ISSUE TITLE
End to end tests for footnotes in Stan User's Guide

### ISSUE THREAD

**Issue by breckbaldwin** [stan-dev/docs#182]
#### Summary:
Footnotes are complete interface code+ stan program examples that reflect the text of the Stan User's Manual. This issue is to discuss design of end to end testing for those programs. 

#### Description:
The footnotes are organized by topic and contain run.py, run.R which simulate data and run the relevant .stan program which is a sister to the interface code.

I propose a simple recursive python program that searches for footnote directories, runs both the python/R code and verifies that no major errors were thrown. 

`import subprocess`
`result = subprocess.run(['Rscript','run.R'], stderr=subprocess.PIPE, stdout=subprocess.PIPE)`
`check(result.stderr)`
`check(result.stdout)`

Note that `check` is not yet implemented.

**Comment by breckbaldwin** [comment]
> Why would search be required for footnote directories? I thought the plan was to have a top-level directory, with one subdirectory per model. Then the model subdirectory might have multiple implementations of the same model. So my question is how we deal with multiple `X.stan` programs, say `linear-regression-simple.stan`, `linear-regression-efficient.stan` in the example we've been discussiong of linear regression? 

I forgot about the reorg into a single dir with footnotes as subdirs. So not search, iterate over the footnote dirs looking for code we want to test. 

>There are lots of models in the user's guide---certainly more than 100 if you count variants getting expanded into whole program.s
> 
The `simple_linear_regression/` footnote dir has 5 .stan programs for example. We will have many more than 100 .stan files at this rate. 

> Is there a plan for multiple `.stan` files in a directory? Does each `X.stan` program get a mathcing `X-run.R` program, so that the search is for `X-run.R` and `X-run.py` files? We should also be checking that each `X.stan` program actually has an `X-run.R` and `X-run.py` file.

There is one `run.R` and an equivalent `run.py` per footnote dir. What seemed natural was to organize a footnote around the narrative in the user's guide and whether the simulated data changed. So `simple_linear_regression/run.R` executes 5 .stan models with variation of data packaging for predictors  and variations of .stan programs that execute differentially with the same data. We have 

- vector (regression_naive.stan, regression_vectorized.stan)
- matrix (regression_matrix.stan) 
- matrix with intercept encoded (regression_matrix_w_intercept.stan, regression_QR.stan)

> What's a major error here? Some of the models we discuss will throw errors like divergences and low effective sample size by design because they're broken, like centered parameterizations of hierarchical GLMs.

The goal is to catch dumb errors at the run.* level and the called *.stan programs. The test will be whether the script completes successfully. This will catch:

- Syntax errors in .stan and .R and .py code
- Runtime errors for .stan that prevent successful fit--maybe more, I don't know all .stan errors that the interfaces allow to kill the execution. 
- Runtime errors for .R and .py

No more detailed analysis than that. 

> 
> So if I'm guessing right, it'll look something like this:
> 
> ```
> footnotes/simple-linear-regression/simple-linear-regression-naive.stan
> footnotes/simple-linear-regression/simple-linear-regression-naive-run.R
> footnotes/simple-linear-regression/simple-linear-regression-naive-run.py
> footnotes/simple-linear-regression/simple-linear-regression-efficient.stan
> footnotes/simple-linear-regression/simple-linear-regression-efficient-run.R
> footnotes/simple-linear-regression/simple-linear-regression-efficient-run.py
> ```

Nope, just one run.R and one run.py. This was an Andrew suggestion. The narrative, at least so far, is based on comparisons of data packaging and Stan programs. Calling multiple .stan programs from the same run.* supports that. 

Once the data really changes then we get a distinct footnote, e.g., `student_t_regression\` is has a slightly different data simulation process so it gets its own footnote. 

The narrative may also force a distinct footnote with the same data. I am just going to have to do some more examples to get a feel for this. 

> Are the tests going to be run with CmdStanR and CmdStanPy (neither of which have official releases) or with RStan and PyStan?

I am using CmdStanR and CmdStanPy. Hopefully they are stable enough at the compile/run/get fit summary at the API level. In any case relatively few people will be writing footnotes/documentation so a little volatility seems ok here but v1.0 would be great to have. 
 
> Is the goal to have this be run via continuous integration?

I don't think CI is called for. It is easy enough to add the tests to the build.py that creates the docs now. The goal is to keep stupid mistakes from making into released documentation.

**Comment by bob-carpenter** [comment]
Thanks---that makes sense.

One more question.  Will all the Stan programs in a directory implement the same model?  That is, will they have the same data declaration, priors, and posterior distribution over all quantities of interest?  That would include things like non-centered reparameterizations, but exclude things like different priors.  

I thought the plan was to generate data from the priors, by which I mean simulating parameters according to the prior and data from the sampling distribution given the parameters generated from the prior, 

```
theta_sim ~ p_{Theta}(theta_sim)
y_sim ~ p_{Y | Theta}(y_sim | theta_sim)
```

If the data's not generated that way, the posterior won't be calibrated and users won't be able to run these programs and expect to get the right posterior interval coverage.

But then that's going to be a problem if we include things like naive centered parameterizations.  Those will have all kinds of divergence problems and give biased results.  I think the decision may have been to just include these models for pedagogical reasons.  That makes it hard to run automated testing.

If the data's not generated that way, the model's misspecified (which just means the data isn't generated by the generative process defined by the model), and it's much harder to evaluate whether we're getting the right posterior because the misspecification means it's no longer going to be calibrated.

So if the goal is to have users see the model recovering parameters within their predicted uncertainties, that is only going to work if the data's generated from the generative model.

**Comment by breckbaldwin** [comment]
> One more question. Will all the Stan programs in a directory implement the same model? That is, will they have the same data declaration, priors, and posterior distribution over all quantities of interest? 

I didn't author the initial data generation for simple_linear_regression, @jgabry did, but I believe the intent is to recover simulating params/distributions from the generating code. I did add some dumb priors to the .stan files to get something there but did not make changes to the generating models. I'll make that change, but I am hoping that more experienced people will help clean that up--paging @andrewgelman. 

I am focused more on getting the right structure worked out overall and not really thinking about quality of models or pedagogy but that will have to happen obviously--hopefully I'll get the feel for it and need less help. 

> That would include things like non-centered reparameterizations, but exclude things like different priors.

My take is we want to try and recover the generating model. On that approach we allow all manner of scaling, centering, repackaging but I am appreciating that this may be too restrictive. When teaching I have done mismatches on purpose like generate normally distributed data and fit with an exponential vs normal and that narrative would have two Stan models with in the same footnote and one run.R. Both the narrative and common generating model support that. 

> 
> I thought the plan was to generate data from the priors, by which I mean simulating parameters according to the prior and data from the sampling distribution given the parameters generated from the prior,
> 
> ```
> theta_sim ~ p_{Theta}(theta_sim)
> y_sim ~ p_{Y | Theta}(y_sim | theta_sim)
> ```

I think we are agreed on this. 

> If the data's not generated that way, the posterior won't be calibrated and users won't be able to run these programs and expect to get the right posterior interval coverage.
> 
> But then that's going to be a problem if we include things like naive centered parameterizations. Those will have all kinds of divergence problems and give biased results. I think the decision may have been to just include these models for pedagogical reasons. That makes it hard to run automated testing.

If the User's guide has models busted enough that it halts the calling process then I have some thinking to do. I wanted to avoid a list of test files/methods with outcomes. Off the top of my head I might use `run_fails.R` as a way to manage both user expectations and keep the testing simple. 

> If the data's not generated that way, the model's misspecified (which just means the data isn't generated by the generative process defined by the model), and it's much harder to evaluate whether we're getting the right posterior because the misspecification means it's no longer going to be calibrated.
> 
> So if the goal is to have users see the model recovering parameters within their predicted uncertainties, that is only going to work if the data's generated from the generative model.

I think we are agreed. @andrewgelman  or others can chime in on this.

**Comment by bob-carpenter** [comment]
> I am focused more on getting the right structure worked out overall 

I know.  That's why I'm trying to jump in now rather than later.  The last question was about how Stan programs are going to be grouped and how the data's going to be generated, not the details of the actual models themselves.

>  I'll make that change, but I am hoping that more experienced people will help clean that

All it requires is generating the parameters from the priors.

> I have done mismatches on purpose like generate normally distributed data and fit with an exponential vs normal and that narrative would have two Stan models with in the same footnote and one run.R. Both the narrative and common generating model support that.

I agree that's a nice pedagogical strategy.  It brings up the issue of what the footnotes are for and whether they're going to introduce narrative content beyond the user's guide.  I had thought @nadrewgelman had stressed he didn't want to do that.   Now we don't have to do what he's suggesting---I'm just trying to understand the scope.

> If the User's guide has models busted enough that it halts the calling process then I have some thinking to do.

I want to stress again this is almost always about how the Stan program is coded, not about the model (depending on whether you define the model as the posterior distribution of quantities of interest or literally the parameter distribution in the posterior---the latter is a more restrictive notion of identity where the centered and non-centered parameterizations constitute truly different models rather than different parameterizations of the same model).

In the problematic posteriors chapter, there are models that return junk because they're not identified or because the parameterization's bad.  These models will not recover simulated parameters in their posteriors.  But I don't think any of them will prevent the sampler from running a large number of iterations.  There might be a couple edge cases that won't initialize because of constraints in the model that aren't respected in the parameter declarations, such as

```
parameters {
  vector[N] sigma;

model {
  sigma ~ lognormal(0, 1);
```

As soon as `N > 10` or so, you're very unlikely to find a legal init in 100 iterations.



For example, the

**Comment by breckbaldwin** [comment]
This discussion is super helpful btw. 

> > I have done mismatches on purpose like generate normally distributed data and fit with an exponential vs normal and that narrative would have two Stan models with in the same footnote and one run.R. Both the narrative and common generating model support that.
> 
> I agree that's a nice pedagogical strategy. It brings up the issue of what the footnotes are for and whether they're going to introduce narrative content beyond the user's guide. I had thought @nadrewgelman had stressed he didn't want to do that. Now we don't have to do what he's suggesting---I'm just trying to understand the scope.

I am explicitly NOT trying to re-write the User's Guide. That is too big and I am not qualified. So if the User's Guide has a mismatch example then I'll keep it in the same footnote. Otherwise I am doing minimal changes to the User's Guide text.

Footnotes will not become some meta/sub-text like a commentary on a pre-Socratic philosopher's fragments. The majority of the value I think is in giving the reader an encapsulated, clear implementation of what is in the User's Guide that unambiguously exercises the User Guide's Stan code. So I agree with Andrew. 

> > If the User's guide has models busted enough that it halts the calling process then I have some thinking to do.
> 
> I want to stress again this is almost always about how the Stan program is coded, not about the model (depending on whether you define the model as the posterior distribution of quantities of interest or literally the parameter distribution in the posterior---the latter is a more restrictive notion of identity where the centered and non-centered parameterizations constitute truly different models rather than different parameterizations of the same model).

Individuation and equivalence of models is going to be slippery I am guessing. This makes me lean harder on the criteria for membership in the same footnote being applied to the same generative model. This then raises the issue that all footnote-common-models are attempts at recovering the same simulation parameters. The models then differ in efficiency, ease-of-understanding and underlying implementation. 

> In the problematic posteriors chapter, there are models that return junk because they're not identified or because the parameterization's bad. These models will not recover simulated parameters in their posteriors. But I don't think any of them will prevent the sampler from running a large number of iterations. There might be a couple edge cases that won't initialize because of constraints in the model that aren't respected in the parameter declarations, such as
> 
> ```
> parameters {
>   vector[N] sigma;
> 
> model {
>   sigma ~ lognormal(0, 1);
> ```
> 
> As soon as `N > 10` or so, you're very unlikely to find a legal init in 100 iterations.

I'd still like to see it fail in the footnote, so I think the `run_fails.*` convention or maybe I can catch the error so it passes as a `run.*` example. 

> 
> For example, the

This dropped off....

**Comment by andrewgelman** [comment]
Just to clarify:  Yes, I think the footnotes should be Stan programs and the necessary R and Stan scripts to simulate fake data and run the Stan projgrams.  I don't think the footnotes should include narrative content.  That way lies madness.  My idea for the footnotes is to make things easier for users.  Right now we can sent a user to chapter 34 in the Stan Users Guide, and that's great:  chapter 34 (or whatever) has great description, some math, some explanation and motivation, and some code snippets.  With the footnotes, the user will be able to immediately jump to runnable, efficiently-coded Stan code, which the user can then incorporate into his or her own project directly.
Andrew

**Comment by andrewgelman** [comment]
I'd recommend against mismatches.  We should definitely include some mismatches in the Bayesian Workflow book, but in the footnotes I recommend keeping it simple, always simulating from the model we are fitting, as the key point here is to get users lined up and able to fit and simulate from these specific models.

**Comment by andrewgelman** [comment]
This all makes sense to me.  Looking forward, we might well have 100 .stan files.  But I don't think we'll be having 5 .stan programs for each model.  I expect we'll move to something like 1 or 2, with 1 program for very clear models that can't be improved, and 2 programs for models where there's one simple implementation and one more computationally efficient implementation.  I might be wrong, but that's my guess.

**Comment by bob-carpenter** [comment]
Yes, this is super helpful.  I like going through the design with a single worked example before going broad.

I think we're all on the same page other than that I'm not sure @andrewgelman caught that we have negative examples---badly coded examples in the user's guide we don't want users to run.  For those, we can just not include footnotes.  That won't help us with making sure the model's grammatical, but it also won't confuse users into using something they shouldn't be using.

**Comment by andrewgelman** [comment]
Yes, that makes sense.

**Comment by breckbaldwin** [comment]
> This all makes sense to me. Looking forward, we might well have 100 .stan files. But I don't think we'll be having 5 .stan programs for each model.

How about I include variations as comments? It would be easy to leave as a comment the non-vectorized version and vectorized.

**Comment by mitzimorris** [comment]
closing - project abandonded.
