### ISSUE TITLE
Typo in User Guide variable declaration

### ISSUE THREAD

**Issue by micmicqb** [stan-dev/docs#186]
#### Summary:
Typo in the User Guide, Section 28.7 Adding group-level predictors

#### Description:
First paragraph in https://mc-stan.org/docs/2_23/stan-users-guide/adding-group-level-predictors.html reads:

> [...]
> then a regression coefficient `psi` can be added for the effect of average state income,
> `real income;`
> 
> with a fixed prior,
> `income ~ normal(0, 2);`

when it should probably read 

> [...]
> then a regression coefficient `psi` can be added for the effect of average state income,
> `real psi;`
> 
> with a fixed prior,
> `psi ~ normal(0, 2);`
#### Current Version:
v2.23.0

**Comment by bob-carpenter** [comment]
Thanks.  We'll fix it.

**Comment by jireva** [comment]
Not sure if this is the right place to add this, but, there's a small bug in one of the example stan programs in the ODEs chapter:

In src/stan-users-guide/odes.Rmd line 585 reads:

    y_sim[t] = matrix_exp((t - 1) * A) * y0;

I think it should be:

    y_sim[t] = matrix_exp(ts[t] * A) * y0;

**Comment by WardBrian** [comment]
Fixed in #300
