### ISSUE TITLE
Adding optimization documentation

### ISSUE THREAD

**Issue by rybern** [stan-dev/docs#193]
#### Summary:
Stanc3's compiler optimizations are currently undocumented. I have created draft documentation, but I don't know where they should go.

#### Description:
Here is my draft of the optimization documentation: https://github.com/rybern/optimization-docs/blob/master/optimization-docs.md
Please let me know (A) how this draft can be improved, and (B) where I should fit them into the docs.

**Comment by SteveBronder** [comment]
Awesome! This circles back around to that there's not really a doxygen like solution for easily making docs for the compiler. Dune [has a doc](https://dune.readthedocs.io/en/stable/documentation.html) generator, but messing with it I've had trouble having both the public and private libraries documented in one site (the html it makes is also kind of ugly tbh)

I'm tempted to post a question on the ocaml subreddit to see how people handle this

**Comment by SteveBronder** [comment]
So for the optimization levels what if we phrased them like [gcc](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) where

1. Each optimization has the level it's turned on at (whether at all)
2. Each optimization level lists it's optimizations and has a line like

> -O3 turns on all optimizations specified by -O2 and also turns on the following optimization flags:

To let users know O2 turns on all of O1 plus yadayada

It may be useful to cleanup the inline example. Even though that is the generated code, pseudo code may make it easier to understand what's happening there

**Comment by rybern** [comment]
Thanks Steve!

> This circles back around to that there's not really a doxygen like solution for easily making docs for the compiler. 

Yeah, I miss [Haddock](https://hackage.haskell.org/package/haddock) :(
Although we'll probably always need something like this doc to explain the user's options and how to use the interface. A Haddock-like solution would be great for actually documenting the code, which certainly needs doing too.

> So for the optimization levels what if we phrased them like gcc where
>
> Each optimization has the level it's turned on at (whether at all)
> Each optimization level lists it's optimizations and has a line like
> -O3 turns on all optimizations specified by -O2 and also turns on the following optimization flags:

Good idea, I'll do this

> It may be useful to cleanup the inline example. Even though that is the generated code, pseudo code may make it easier to understand what's happening there

Yeah, I thought I would try to use a cleaned up version of the real mir-pretty printouts to prepare people to read those if they need to. I think most of them are readable, would it be sufficient to clean up or explain the function inlining example? There's some code generation I forgot to explain there (like why there's a loop).

**Comment by rok-cesnovar** [comment]
The docs are great! I think it would be better to group the descriptions by the proposed levels.

Would it be possible to have an unoptimized and optimized MIR side-by-side?

**Comment by SteveBronder** [comment]
Couple random Qs about the optims

- Doesn't expression propagation cause computation of the same thing multiple times?
- Is there a limit to the static loop unrolling? I imagine that could end up being bad if we unroll a 1:1000 loop
- gcc seems to do the opposite of `Constant propagation` with `-fmerge-constants`? Idk how those two would interact. Maybe it would let gcc have the opportunity to make some constants [immediate](https://en.wikichip.org/wiki/immediate_value)
- gcc has an optim for inline functions only called once which may be nice for us as well to have in O1.

Are multiple passes of these optimizations performed if they are turned on?

**Comment by SteveBronder** [comment]
Also here's a weird one, a side side note. If a user told us a looping variable had a lower bound value of 4 like `int<lower=4> N;` we could unroll loops to give the compiler better opportunities for SIMD operations like

```cpp
// pseudocode
N_mod = mod(N);
for (int i = 0; i < N - N_mod; ++i) {
  x[i] = y[i]
  x[i + 1] = y[i + 1]
  x[i + 2] = y[i + 2]
  x[i + 3] = y[i + 3]
}
// rest of loop
for (int i = N - N_mod; i < N; ++i) {
   x[i] = y[i];
}

```

**Comment by SteveBronder** [comment]
> Yeah, I miss Haddock :(
> Although we'll probably always need something like this doc to explain the user's options and how to use the interface. A Haddock-like solution would be great for actually documenting the code, which certainly needs doing too.

Yeah Haddock looks rad I've tried multiple times to get a nice doc solution for the compiler. I think what we need to do is to call the dune doc thing for both public and private, and then have I guess have a custom page that links to them? tbh could use something like bookdown or whatever to make the main page

**Comment by rybern** [comment]
> The docs are great! I think it would be better to group the descriptions by the proposed levels.

Yeah, I think I'm going to combine yours and Steve's suggestion and organize by the optimizations that are added at each level.

> Would it be possible to have an unoptimized and optimized MIR side-by-side?

Like physically side by side, as in a table? That might be cool. I didn't include the unoptimized MIR because I thought it would be too verbose and I knew I wanted to include the program.

**Comment by rybern** [comment]
> Couple random Qs about the optims
> 
> * Doesn't expression propagation cause computation of the same thing multiple times?

Yep! That's why lazy code motion should be applied after expression propagation, it undoes that damage.

> * Is there a limit to the static loop unrolling? I imagine that could end up being bad if we unroll a 1:1000 loop

There is no limit set, that could indeed be bad

> * gcc seems to do the opposite of `Constant propagation` with `-fmerge-constants`? Idk how those two would interact. Maybe it would let gcc have the opportunity to make some constants [immediate](https://en.wikichip.org/wiki/immediate_value)

Interesting, not sure what the answer is. Constant prop is still good for partial evaluation, but currently lazy code motion does not pull the constants back out (IIRC). Maybe it should, that would be an easy change.

> * gcc has an optim for inline functions only called once which may be nice for us as well to have in O1.

This would require some work. It's currently done recursively in one pass (excluding recursive functions). Wouldn't be too hard if folks wanted it.

> Are multiple passes of these optimizations performed if they are turned on?

Yes, some of them are. I think I mentioned it somewhere in the doc.

> Also here's a weird one, a side side note. If a user told us a looping variable had a lower bound value of 4 like int<lower=4> N; we could unroll loops to give the compiler better opportunities for SIMD operations like

Yeah, could definitely do that. Taking better advantage of loop structure has some real possibilities.

> I think what we need to do is to call the dune doc thing for both public and private, and then have I guess have a custom page that links to them? tbh could use something like bookdown or whatever to make the main page

That would be great, honestly whatever you're willing/able to put together would be highly appreciated.

**Comment by rok-cesnovar** [comment]
> I didn't include the unoptimized MIR because I thought it would be too verbose and I knew I wanted to include the program.

The before/after comparison is easier to process for me at least.

**Comment by rybern** [comment]
@SteveBronder @rok-cesnovar Updated the doc draft with your suggestions: https://github.com/rybern/optimization-docs/blob/master/optimization-docs.md

I'd like to integrate this into the existing docs somewhere so that we can move this into a PR. Where do you think it should go?

**Comment by rok-cesnovar** [comment]
The docs look great! I think the before/after works nice. Makes it easy to understand.

I am not sure of the location, I am really not super familiar with this repository, to be honest. That is also more of a question for folks that have experience teaching Stan.

**Comment by SteveBronder** [comment]
I think the reference manual would be the right place for this. With all the compiler flags like diagnostic mode etc. maybe we should have a new section on compiler options

**Comment by SteveBronder** [comment]
Docs look good tho! One little thing

> O3 includes optimizations specified by O1 and also:

O3 includes optimizations specified by ~O1~ O2 and also:

**Comment by bob-carpenter** [comment]
Yes.  The description of functionality should all go in the reference manual.  Then anything user-facing about how to use it that's narrative and informal should go in the user's guide.

**Comment by rybern** [comment]
Makes sense, thanks.
