### ISSUE TITLE
Adding Pedantic Mode documentation

### ISSUE THREAD

**Issue by rybern** [stan-dev/docs#194]
#### Summary:
Pedantic Mode should be landing in Stanc3 soon. I have a draft of the documentation, but I need feedback and I don't know where it should end up.

#### Description:
Here is my draft of the Pedantic Mode documentation: https://github.com/rybern/pedantic-mode-doc/blob/master/pedantic-mode-doc.md
I could use feedback on this document and guidance on where to put it. If I knew where to put it, I could open a PR for feedback.

Related discussion here: https://discourse.mc-stan.org/t/pedantic-mode-is-ready-for-your-testing-and-feedback/13893/2

**Comment by jgabry** [comment]
@rybern Thanks for this. I'm also not sure where this doc should go. I would say either in the Stan User's Guide (`docs/src/stan-users-guide`) or the Stan Language Reference Manual (`docs/src/reference-manual`). I could see an argument either way, but probably not the Stan Functions Reference. 

@mitzimorris and @bob-carpenter I know you both have done a lot of work organizing the doc, so do you have a preference for this one?

**Comment by bob-carpenter** [comment]
The spec of what it does from a high level should go in the reference manual.  Hints for users on how to use it should go in the user's guide.  The latter is optional.

**Comment by rybern** [comment]
Thanks, I'll do some formatting and put together a PR.
