### ISSUE TITLE
some functions return the type R rather than real

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/docs#197]
#### Summary:
I'm not completely sure if this is a bug, but it's indicated that some functiond return an element of the type R, but I can't find the type R anywhere, is this supposed to be real?

#### Example:
R fabs(T x)
real fdim(real x, real y)

But there are many more.

#### Current Version:
v2.23.0

**Comment by mitzimorris** [comment]
`real` is a scalar,  R is any dimensional real?

**Comment by bnicenboim** [comment]
isn't that reals or real[]?
(I also don't know the difference between them)

**Comment by bob-carpenter** [comment]
Sounds like we need to clarify the conventions.  I used the `R` and `T` rather like template parameters in C++.  For functions where they used, they get instantiated in various ways.   And each such use should at least point to a description of how the template types (capital letters like `R` and `T`) get instantiated.

The use of `reals` indicates that any of `real`, `real[]`, `vector`, or `row_vector` can be used.  But there's no dependency.  So we have things like:
```
real normal_lpdf(reals y, reals mu, reals sigma)
```
That's different than
```
T foo(T x);
```
which says the output type is the same as the input type.  For all the cases where we have template uses like this, we should explain the instantiations.  

For `fabs` and other continuous math lib functions, the intended signatures are at least

```
real fabs(real x);
real fabs(int x);
real[] fabs(real[] x);
real[] fabs(int[] x);
vector fabs(vector);
row_vector fabs(row_vector);
```

The return type promotes `int` to `real`, so they don't always match.

**Comment by bnicenboim** [comment]
Just one clarification question, then `R foo(R x);` and `T foo(T x);` are the same right?

**Comment by bob-carpenter** [comment]
> Just one clarification question, then R foo(R x); and T foo(T x); are the same right?

Yes.  We should just stick to `T` when the argument type matches the return type, but I or someone else might've used `R` if it's restricted to real values.

> But there is also R foo(T x); in the manual...

Thats for functions like fabs(x) that always return real even if their input is integer.
