### ISSUE TITLE
Minor typos in Stan user guide

### ISSUE THREAD

**Issue by karldw** [stan-dev/docs#208]
#### Summary:

I noticed a couple of typos in the Stan user guide v2.23.0. I thought it might be helpful to let you know. The page numbers below refer to the PDF version of the docs: https://mc-stan.org/docs/2_23/stan-users-guide-2_23.pdf

#### Description:

1. p334: I think `x_rep` is meant to be `y_rep`.
1. p335: "There is a" seems to be missing the rest of the sentence.
1. It seems that `normal_rng` returns an array of reals, rather than a vector. This behavior surprised me, and means the following examples don't compile:
    - p334: `vector[N] y_rep = normal_rng(alpha + beta * x, sigma);`
    - p344: `vector[K] alpha_rep = normal_rng(rep_vector(mu, K), sigma);`

Is #&#8203;3 a bug in stanc3, rather than a typo in the docs?

#### Additional Information:
Thanks for the detailed user guide!

Also, the [search link](https://github.com/stan-dev/docs/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3ABug%20%22next%20release%20documentation) in [CONTRIBUTING.md](https://github.com/stan-dev/docs/blob/master/.github/CONTRIBUTING.md) returns no results.

#### Current Version:
v2.23.0

**Comment by mitzimorris** [comment]
thanks very much for the careful reading - will fix!

**Comment by mitzimorris** [comment]
> It seems that `normal_rng` returns an array of reals, rather than a vector. This behavior surprised me, and means the following examples don't compile:
> * p334: `vector[N] y_rep = normal_rng(alpha + beta * x, sigma);`
> * p344: `vector[K] alpha_rep = normal_rng(rep_vector(mu, K), sigma);`

I'll take a look

**Comment by mitzimorris** [comment]
regarding `real y_rep[N]` vs `vector[N] y_rep` - it's an oversight in the user's guide, not a bug in the Stanc3 compiler.

that definition uses type `R` -  in the prng-vectorization section, 10.8.3.3 Return type - it says:

> The result of a vectorized PRNG function depends on the size of the arguments and the distribution’s support. If all arguments are scalars, then the return type is a scalar. For a continuous distribution, if there are any non-scalar arguments, the return type is a real array ( `real[]` ) matching the size of any of the non-scalar arguments, as all non-scalar arguments must have matching size. Discrete distributions return  `ints`  and continuous distributions return  `reals` , each of appropriate size. The symbol  `R`  denotes such a return type.

in short, the vectorized RNG function `normal_rng` return scalars or `int` or `real` arrays.  not `matrix`, `vector`, or `row_vector`.

will add this to the User's Manual

**Comment by mitzimorris** [comment]
made corrections, pushed to master.  see discussion here: https://discourse.mc-stan.org/t/why-dont-vectorized-rngs-return-vectors-when-given-vector-input/16328

**Comment by jgabry** [comment]
Thanks @karldw, and thanks @mitzimorris for fixing these!
