### ISSUE TITLE
pygmentize manual

### ISSUE THREAD

**Issue by syclik** [stan-dev/docs#21]
Update manual so there is:
- syntax highlighting for Stan code
- code split out into separate files
- test code segments for syntactic correctness against parser

**Comment by bob-carpenter** [comment]
The pygment thing should be independent of splitting out code.

The blocker for testing code is that we don't have a fragment checker or a way to pull fragments out of a separate file and into the doc.  We could check whole programs, but there are actually very few of those in the doc now.

**Comment by WardBrian** [comment]
Cleaning up old issues: I believe this was resolved by #465 which added highlighting. Checking code fragments is possible, but as Bob pointed out there aren't that many genuinely complete fragments to parse
