### ISSUE TITLE
`build.py` produces a seg fault

### ISSUE THREAD

**Issue by charlesm93** [stan-dev/docs#221]
#### Summary:
Most of the time, when I run build.py, I get a segfault error message. However, the doc still seems to get correctly build.

#### Description:
Here's the error message:
```
 *** caught segfault ***
address 0x10afbfffc, cause 'memory not mapped'

Traceback:
 1: paste(x, ..., collapse = "\n")
 2: one_string((knit_hooks$get("document"))(res))
 3: knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
 4: rmarkdown::render(main, output_format, ..., clean = clean, envir = envir)
 5: render_cur_session(files, main, config, output_format, clean,     envir, ...)
 6: bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook")
An irrecoverable exception occurred. R is aborting now ...
Command Rscript -e "bookdown::render_book('index.Rmd', output_format='bookdown::gitbook')" failed
Traceback (most recent call last):
  File "./build.py", line 113, in <module>
    main()
  File "./build.py", line 109, in main
    make_docs(docspath, stan_version, doc, formats)
  File "./build.py", line 54, in make_docs
    shexec(command)
  File "./build.py", line 35, in shexec
    raise Exception(returncode)
Exception: -11
```
This is observed after installing all the required packages, on Mac OS Catalina, with R 3.6.2.

#### additional information

See discourse thread: https://discourse.mc-stan.org/t/error-compiling-docs-using-build-py/16526/8

#### Current Version:
v2.23

**Comment by mitzimorris** [comment]
how is this different from issue #219 ?

**Comment by charlesm93** [comment]
My reading is that #219 is about error messages, while this is a potential compilation issue. That said, I don't mind closing this issue and commenting in #219, if this is more helpful.

**Comment by mitzimorris** [comment]
all of your comments have been extremely useful!

I think the segfault problem is coming from the fact that the src files for the user's guide include a file `simple_examples.Rmd` which tries to run and compile a bunch of Stan models.

this file has been there all along - it's a chapter in what will be the Bayesian workflow book.
before the docs repo, there was a different repo called `stan-book` or something like that;
files got moved around and renamed, and that file came along for the ride.

for some reason bookdown isn't just compiling the .Rmd files listed in file `_bookdown.yml`,
it's trying to compile all .Rmd files in the stan user's guide directory.   does this make sense?

I just deleted this file from `master`.  if this is indeed the problem, then pulling from master,
also removing directory `_bookdown_files` and any `main.*` files left lying around in src
should fix this - maybe - could you please try this?

**Comment by mitzimorris** [comment]
cleaned up docs src code, should build now.
