### ISSUE TITLE
Document suite of hmm functions

### ISSUE THREAD

**Issue by charlesm93** [stan-dev/docs#222]
#### Summary:
Add documentation for hmm functions: `hmm_marginal`, `hmm_latent_marginal_prop`, and `hmm_latent_rng`.

#### Additional Information:
Pull request describing the function https://github.com/stan-dev/math/pull/1868

#### Current Version:
v2.18.0

**Comment by charlesm93** [comment]
It's not entirely clear to me where in the function references I should document the hmm routines. Typically, `hmm_marginal` would appear on the rhs of `target +=`, so I think of it as a distribution. But it doesn't take in the data `y` (the data is implicitly passed through the matrix `omega` and depending on the model, `y` can be discrete or continuous). As such neither the discrete nor the continuous distribution are appropriate terms.  

I could either create a new section for distributions (additional distributions -- which could come in handy in the future), or write the hmm functions under matrix operations.

**Comment by SteveBronder** [comment]
I like the idea of additional distributions personally

**Comment by bob-carpenter** [comment]
@charlesm93:   I agree with @SteveBronder that it's better with the distributions than the matrix functions.  Either way, I think it should be its own chapter.   The probability functions are organized by type of variable (binary, discrete, continuous, positive, positive-definite matrix, etc.).  The type here is a generic sequence type, so it should get its own chapter.
