### ISSUE TITLE
caught a typo in the documentation

### ISSUE THREAD

**Issue by aaelony** [stan-dev/docs#224]
#### Summary:
In https://mc-stan.org/docs/2_23/functions-reference/index.html, please replace 

```
<p><a href="https://github.com/stan-dev">https://github.com</a></p>
```

with 

```
<p><a href="https://github.com/stan-dev">https://github.com/stan-dev</a></p>
```

see: https://github.com/stan-dev/docs/blob/master/docs/2_23/functions-reference/index.html#L610

Cheers,
-A

**Comment by mitzimorris** [comment]
oops - many thanks - fixing immediately!

**Comment by mitzimorris** [comment]
fixed!
