### ISSUE TITLE
RNG prohibited in transformed data?

### ISSUE THREAD

**Issue by rybern** [stan-dev/docs#226]
This line isn't correct as far as I know:
https://github.com/stan-dev/docs/blob/3bb2cf5538b45f6512be074137834e4196871875/src/reference-manual/blocks.Rmd#L392

**Comment by mitzimorris** [comment]
entirely correct.
this should have been removed a long time ago.  will fix ASAP.

**Comment by mitzimorris** [comment]
fixed on master
