### ISSUE TITLE
add doc for number of decimal places of CSV/comment output

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/docs#229]
#### Summary:

The doc should indicate the precision of the ASCII output.  

#### Description:

Longer term, we'll want to control the precision, but now it's fixed and we should mention what it is.

#### Current Version:
v2.17.1

**Comment by mitzimorris** [comment]
precision is at mode 6 decimal places.  documented.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/docs/pull/241
