### ISSUE TITLE
document cmdstan csv format, especially for arrays

### ISSUE THREAD

**Issue by tpapp** [stan-dev/docs#230]
Looking at the code and examples, I think that the following holds:

1. for array (matrix, vector, etc) variables, column names `varname[i,j,k]` appear as `varname.i.j.k` in the CSV header line,
2. for the same `varname`, the range of colums is contiguous, ie one cannot have `a.1, b, a.2` columns in the posterior dump,
3. within the contiguous block, array elements are in column major order
4. for arrays of vectors/matrices, the same arrangement applies as in the data dump

Are the above true?
Could they be briefly documented in an Appendix of the CmdStan manual?
This would be helpful as I am writing a tool that parses these files.

**Comment by mitzimorris** [comment]
documented in CmdStan guide appendix on Stan CSV format
