### ISSUE TITLE
user guide out of sync

### ISSUE THREAD

**Issue by wds15** [stan-dev/docs#234]
#### Summary:

Currently the user guide needs update here:

- RTools 4.0 is not really covered as it requires more steps
- Section B.8 on parallelisation support has links to math which do not exist any more.

#### Current Version:
v2.23.0

**Comment by wds15** [comment]
Thanks.... and I noticed that finding the threading info is hard, because its buried in the appendix so that it is not listed in the TOC. If we can do something about that, it would be good.

**Comment by mitzimorris** [comment]
to address these issues, planning on adding the following:

- "CmdStan Installation" chapter - subsections for platforms Mac, Linux, and Windows
- "Compiling a Stan Program" chapter - subsections on threading, gpus

can also add appendix sections.  there's no index, but the HTML docs to have gitbook's built-in "search"

**Comment by mitzimorris** [comment]
added chapter on "Parallelization" to describe compiling and running threading and GPU programs.
