### ISSUE TITLE
add links to latest to 2.23 docs 

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#239]
#### Summary:
For the Stan/CmdStan 2.24 release, we need to update the 2.23 docs so that they link to latest.

#### Description:
When viewing docs for an old version, page should display message at top:
" This is an old version, view current version."

E.g.  - https://mc-stan.org/docs/2_22/stan-users-guide/index.html

currently, https://mc-stan.org/docs/2_23/stan-users-guide/index.html
is missing these messages.
This is Inserted by script `add_links.sh` - is this supposed to happen automatically?

#### Current Version:
2.23.0

**Comment by mitzimorris** [comment]
@serban-nicusor-toptal - I can do this via script myself - unless this is going to be done automatically at some point.

**Comment by serban-nicusor-toptal** [comment]
Hey @mitzimorris we're handling that [here](https://github.com/stan-dev/docs/blob/master/Jenkinsfile) through Jenkins but on this release, the docs for 2.24 were already built so I thought this was already done too.
I ran the job and it created [this](https://github.com/stan-dev/docs/pull/240) PR if you can take a look and approve, thanks!
It also created [this](https://github.com/stan-dev/stan-dev.github.io/pull/125) PR for stan-dev.github.io.

Please let me know if there's anything else to be done, sorry for the inconvenience.

**Comment by mitzimorris** [comment]
many thanks!
the docs for 2_24 were built ahead of the release to make it easier for the devs and reviewers to see the docs that got added for all the new great stuff in 2_24, so they were published without adding links to the 2_23 release.  if this happens again, we'll do a better job of co-ordinating with you.
