### ISSUE TITLE
Missing funnel.figure

### ISSUE THREAD

**Issue by aaelony-catasys** [stan-dev/docs#246]
Reading through the online documentation [hierarchial priors section](https://mc-stan.org/docs/2_24/stan-users-guide/hierarchical-priors-section.html) reads to "See the 
plot of Neal’s funnel density", but that links to "https://mc-stan.org/docs/2_24/stan-users-guide/hierarchical-priors-section.html#funnel.figure" which doesn't appear to actually have a plot currently.

Regards,
A

**Comment by jgabry** [comment]
@aaelony-catasys Thanks for reporting this. That link definitely doesn't go anywhere. 

@mitzimorris I think this is coming from 
https://github.com/stan-dev/docs/blob/33e4f5af9a7368a96fc45f04c300ccdb40e94439/src/stan-users-guide/regression.Rmd#L882

Linking with `#funnel.figure` doesn't lead anywhere. Should `#funnel.figure` link to a doc section that has the image in it or the image itself? Here's the image file 

https://github.com/stan-dev/docs/blob/master/src/stan-users-guide/img/funnel.png 

but maybe the intent was to link to this whole section

https://mc-stan.org/docs/2_24/stan-users-guide/reparameterization-section.html

**Comment by mitzimorris** [comment]
added an html anchor tag in appropriate section (effeciency tuning), link to anchor name in regression chapter (sec 1.10)

**Comment by jgabry** [comment]
Great thanks!

**Comment by aaelony-catasys** [comment]
super!
