### ISSUE TITLE
Typos in MRP chapter of Stan users guide 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/docs#249]
* In 28.6 `epsilon` is in the parameters block but not used anywhere in the model

* In 28.7 it says it will introduce `psi` but then uses 

```
real income;
```

and

```
income ~ normal(0, 2);
```

but it should be 

```
real psi;
```

and 

```
psi ~ normal(0, 2)
```

Will follow up if I notice more as I go through the chapter.

**Comment by mitzimorris** [comment]
good catch - anything more?

**Comment by jgabry** [comment]
That's all I've found so far

**Comment by micmicqb** [comment]
In 28.4, the subscripts and superscripts in the sums over k and m do not render properly -- my guess looking at the rendering is that there are some missing {} around the subscripts k=1 and m=1.

**Comment by bob-carpenter** [comment]
My bad.  I proofread twice, but it's hard to proofread 60 pages of your own writing.  I can fix it if this is all you've found so far.
