### ISSUE TITLE
PDF user guide is all centered after p171

### ISSUE THREAD

**Issue by karldw** [stan-dev/docs#251]
#### Summary:
I noticed the PDF version of the user manual v 2.24.0 has all-centered text after page 171.

#### Description:
Both the text and the headings are centered, which leads to some weird spacing like the screenshot below.

I'm guessing there's some issue with the `\centering` escaping the ODE figure at the top of p171. Some latex code was printed as text.

![manual-screenshot](https://user-images.githubusercontent.com/12504708/89359664-e05f7b80-d6b5-11ea-8f4c-df68f92d3d96.png)

#### Current Version:
v2.24.0

**Comment by mitzimorris** [comment]
whoa!! will investigate ASAP - many thanks for the report.

**Comment by mitzimorris** [comment]
things run off the rails in the "measurement error models" section.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/258
