### ISSUE TITLE
CmdStan User's Guide - document "Aki trick" to see initial parameter values

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#255]
#### Summary:
https://discourse.mc-stan.org/t/does-the-init-argument-work-with-cmdstanr/17255/16

#### Description:
per discussion on discourse - by running the sampler with fixed params and
inspecting the Stan csv output file, you can see all of the parameter values
*reported on the constrained scale* which corresponds to how they are specified
by the user.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by jgabry** [comment]
Hopefully eventually this can be removed and we can actually provide access to initial values, but yeah it would be great to document this until then. I just opened an issue at `stan-dev/stan`: https://github.com/stan-dev/stan/issues/2950

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/docs/pull/261
