### ISSUE TITLE
Missing pedantic mode docs on website

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/docs#263]
#### Summary:

I think pendantic mode should show up below "Diagnostic Mode" in the reference manual but it does not: https://mc-stan.org/docs/2_24/reference-manual/index.html

Here is the pull request where it went in: https://github.com/stan-dev/docs/pull/201/files

I assume this just means the reference manual needs rebuilt.

**Comment by mitzimorris** [comment]
damn, I republished and they're not showing up.
will investigate.

**Comment by mitzimorris** [comment]
fixed - did another commit and push and now it's there.
