### ISSUE TITLE
RNG functions in docs - can be called from transformed data as well as gq block

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#28]
#### Summary:
The PRNG functions are available in the transformed data blocks as well as in generated quantities block - this is correctly documented in the users guide and reference manual but the functions reference needs to be updated.

#### Description:
Stan issue https://github.com/stan-dev/stan/issues/1644 changed the Stan language to allow calls to RNG functions in the transformed data block.  The documentation in the functions reference manual need to be changed from statements like: 
> may only be used in generated quantities block

to 

>  may only be used in transformed data and generated quantities block

#### Additional Information:
cross-reference to section in user's guide?

#### Current Version:
v2.18.0

**Comment by mcol** [comment]
This can be closed.
