### ISSUE TITLE
cmdstan-guide url still points to 2.24

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/docs#284]
#### Summary:
The url for the cmdstan guide, https://mc-stan.org/docs/cmdstan-guide/stanc.html, seems to still point to 2.24 when I see that 2.25 is up and working at https://mc-stan.org/docs/2_25/cmdstan-guide/stanc.html.

**Comment by mitzimorris** [comment]
good catch.

@serban-nicusor-toptal - the release scripts need to update links in `src/cmdstan-guide` - do they?

**Comment by serban-nicusor-toptal** [comment]
In the [pipeline](https://github.com/stan-dev/docs/blob/master/Jenkinsfile) we're building the docs, adding redirects and linking to latest, afaik that should have covered it. Did I miss a step ?

**Comment by mitzimorris** [comment]
thanks for checking @serban-nicusor-toptal  - will check to see what the problem with this particular link is.

**Comment by mitzimorris** [comment]
we need to add call to "add-redirects" script for cmdstan-guide in the above pipeline here:  https://github.com/stan-dev/docs/blob/aa89620638962751b8a193347edec6f6ebd72001/Jenkinsfile#L52

ran the script manually and pushed changes.

**Comment by serban-nicusor-toptal** [comment]
Fixed [here](https://github.com/stan-dev/docs/commit/defa384a31800d97e4f90c1cb4770fea2277a562) thanks @mitzimorris !
