### ISSUE TITLE
simplify R package dependencies - use of package `arm`?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#286]
#### Summary:
R packages used by docs include old package `arm` as well as bookdown - investigate where this functionality is used, if possible replace.

#### Description:
Building the docs locally requires installations of both Python and R as well as latex for pdfs.

For maintainability and ease of new developer use, we should use the minimal amount of extra modules and packages as well as document clearly the tools needed to build the docs from scratch.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by WardBrian** [comment]
Is this still relevant? I think a lot of the R dependencies were trimmed out in #390 right?
