### ISSUE TITLE
Docs for lupmf/lupdf

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/docs#287]
#### Summary:

We have function guide docs for the `_lupmf` and `_lupdf` functions. We need user's guide docs and reference manual docs.

Additional discussion here: https://discourse.mc-stan.org/t/lupdf-functions-where-how-to-doc-them/18792/24

#### Current Version:
v2.18.0

**Comment by rok-cesnovar** [comment]
Fixed in #288
