### ISSUE TITLE
There is an error in the rng for the truncated normal

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/docs#29]
#### Summary:

In https://mc-stan.org/docs/2_18/stan-users-guide/truncated-random-number-generation.html
all the examples with `normal_rng` should have inv_Phi instead of Phi. See also https://discourse.mc-stan.org/t/rng-for-truncated-distributions/3122/10.

(I can also fix it myself, but should I do a pull request to master?)
#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
Thanks for reporting.  We can fix.  I'm closing here and moved your bug report to here:

https://github.com/stan-dev/docs/issues/15#issuecomment-466066519

We'll get the location of all these things sorted out.
