### ISSUE TITLE
Conditions for Jacobian adjustments

### ISSUE THREAD

**Issue by jsocolar** [stan-dev/docs#292]
Currently, section 21.3 **Changes of variables** begins (second paragraph):
> The change of variables requires an adjustment to the probability to account for the distortion caused by the transform. For this to work, univariate changes of variables must be monotonic and differentiable everywhere in their support.
>
> For univariate changes of variables, the resulting probability must be scaled by the absolute derivative of the transform.

Although the document eventually addresses multivariate changes of variables in more detail, it never mentions the conditions required for the multivariate change of variables to work. These are that the change of variables be injective, differentiable everywhere in its support, and map **R**<sup>n</sup> to **R**<sup>n</sup>.

Also, as currently written, section 21.3 starts using the term "Jacobian adjustment" in the univariate case without explaining where the term comes from.

I suggest changing the paragraphs quoted above to:
> The change of variables requires an adjustment to the probability to account for the distortion caused by the transform. For this to work, univariate changes of variables must be monotonic and differentiable everywhere in their support. Multivariate changes of variables must be injective and differentiable everywhere in their support [and must map **R**<sup>n</sup> to **R**<sup>n</sup>].
>
> The probability must be scaled by a *Jacobian adjustment* equal to the absolute determinant of the Jacobian of the transform. In the univariate case, the Jacobian adjustment is simply the absolute derivative of the transform.

Hopefully this explains the multivariate case and introduces the term *Jacobian adjustment* without impacting the accessibility of the writing too much (bearing in mind that "monotonic" is less scary than "injective"; "derivative" is less scary than the determinant of a 1x1 Jacobian).  

I'm ambivalent about the clause in square brackets. Perhaps the fact that the correction requires the determinant of the Jacobian is already sufficient to get the point across.

While we're here anyway, it would good to change `log of the Jacobian` to `log of the absolute determinant of the Jacobian` in the first sentence of the **Multivariate changes of variables** sub-section.

If these changes would be welcome I'm happy to make a pull request (also happy for somebody else to just do it).

#### Current Version:
v2.18.0

**Comment by jgabry** [comment]
Thanks, yeah a PR would be great. I think these changes are good. Someone may suggest edits if you make a PR but I think this or something close to it would get merged.

**Comment by jgabry** [comment]
Closing now that #297 is merged. Thanks again.
