### ISSUE TITLE
New array syntax needs documentation

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/docs#296]
#### Summary:

The new array syntax that was part of the stanc3 pull https://github.com/stan-dev/stanc3/pull/714 needs documentation

@rok-cesnovar @rybern can either of you edit this issue and add links to the relevant discourse/design discussions so that whoever writes this has the information they need?

#### Current Version:
v2.25.0

**Comment by rok-cesnovar** [comment]
Some additional discussion links:
- https://discourse.mc-stan.org/t/new-array-declaration-syntax/16011

- https://discourse.mc-stan.org/t/new-array-syntax-might-mean-stan-language-3-0/17448/15

**Comment by rok-cesnovar** [comment]
Do we have any volunteers for this? The signature errors in stanc3 now report the signature with the array syntax (the old one obviously still works). At minimum we should add at least a few lines that `arrray[] real` is equivalent to `real[]`.
