### ISSUE TITLE
GLM functions have disappeared from functions reference / reference manual

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/docs#30]
#### Summary:
The GLM functions
`bernoulli_logit_glm`
`neg_binomial_2_log_glm`
`normal_id_glm`
`poisson_log_glm`
do not appear in the functions reference or reference manual anymore, though they definitely used to be in there.

#### Description:
I wrote manual entries for these functions when I originally submitted my PRs, but they seem to have disappeared in the version of the doc for 2.18 on https://mc-stan.org/users/documentation/ .

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by VMatthijs** [comment]
@mitzimorris , do you have an idea of what may have happened here?

**Comment by mitzimorris** [comment]
are these functions available in 2.18 release or did they go in after it?
will check what's up.

**Comment by bob-carpenter** [comment]
Didn't some of the doc changes get blown away in a recent merge?  That's what I was asking about looking for.  

I'm even more concerned about bug patches to the doc not getting propagated.

**Comment by VMatthijs** [comment]
They should be in 2.18. I added them a long time ago. Thanks, @mitzimorris !

**Comment by mitzimorris** [comment]
they are most definitely not lost - it's GitHub! - will track them down and make sure they're in the docs.

**Comment by mitzimorris** [comment]
they are there in the source:  
bernoulli_logit_glm  see: Bernoulli-Logit Generalised Linear Model (Logistic Regression)  -
https://github.com/stan-dev/docs/blob/b692b2bb0cb299dfd36aa53ca48520944a33f326/src/functions-reference/binary_distributions.Rmd#L110

neg_binomial_2_log_glm
https://github.com/stan-dev/docs/blob/b692b2bb0cb299dfd36aa53ca48520944a33f326/src/functions-reference/unbounded_discrete_distributions.Rmd#L191

normal_id_glm
https://github.com/stan-dev/docs/blob/b692b2bb0cb299dfd36aa53ca48520944a33f326/src/functions-reference/unbounded_continuous_distributions.Rmd#L119

poisson_log_glm
https://github.com/stan-dev/docs/blob/b692b2bb0cb299dfd36aa53ca48520944a33f326/src/functions-reference/unbounded_discrete_distributions.Rmd#L334


I can regenerate and publish the manual from the source so it's there online.

**Comment by VMatthijs** [comment]
Fantastic! Thanks, @mitzimorris !

**Comment by mitzimorris** [comment]
@VMatthijs - were affine transforms offset/multplier added to 2.18 or is this a 2.19 feature?

**Comment by VMatthijs** [comment]
Those were a 2.19 feature

**Comment by mitzimorris** [comment]
checked online Stan functions reference - GLMs are there -
https://mc-stan.org/docs/2_18/functions-reference/neg-binom-2-log-glm.html
etc.

**Comment by mitzimorris** [comment]
regenerated 2_18 manuals, all there.
https://github.com/stan-dev/docs/pull/33

**Comment by VMatthijs** [comment]
Thanks! It seems like they're still not in the pdf version, though. :-/

**Comment by VMatthijs** [comment]
The reason I like the pdf version, by the way, is that the index is missing in the html version, which is the part of the functions reference I use the most.

**Comment by mitzimorris** [comment]
what are you looking for in the pdf?

**Comment by mitzimorris** [comment]
there's a search box on the html pages - it works pretty well

**Comment by mitzimorris** [comment]
they are in the pdf - 
https://github.com/stan-dev/docs/blob/master/docs/2_18/functions-reference-2_18.pdf
search for "generalised"

the pdf linked to from documentation page is linked to pdfs for 2.18.0 release - I will update that link.

**Comment by bob-carpenter** [comment]
I don't think it's clear from the page layout to most people that there's a search function that goes beyond the current page.  It wasn't to me.

The other problem with search functions is that you can't get in the general neighborhood and browse easily. 

So it'd be great to actually generate an index for the functions reference.

My original thinking was that each function would be a page and that would make hte table of contents the index.  But then I don't know how to impose higher-level structure on the function reference manual that way.
