### ISSUE TITLE
Documentation for log_inv_logit_diff is missing

### ISSUE THREAD

**Issue by maxmantei** [stan-dev/docs#302]
#### Summary:
The function ``log_inv_logit_diff`` has been exposed to the Stan language, but its documentation is still missing from the Stan Functions Reference.

#### Description:
Documentation for ``log_inv_logit_diff`` is missing in the Stan Functions Reference [3.14 Composed Functions](https://mc-stan.org/docs/2_25/functions-reference/composed-functions.html). Since the function is vecorized, the documentation for it could look something like this:

>``R`` **``log_inv_logit_diff``** ``(T1 x, T2 y)``
natural logarithm of the difference of the inverse logit function of x and the inverse logit function of y.

#### Additional Information:
The LaTeX representation (in case it should be included as well):
\mathrm{log\_inv\_logit\_diff}(x,y) = \log(\mathrm{inv\_logit}(x) - \mathrm{inv\_logit}(y))

The function can be useful when one wants to code a customized version of an ordered logit model, e.g. an ordered multinomial logit model.

#### Current Version:
v2.25.0

**Comment by andrjohns** [comment]
Thanks for catching this Max! I originally added the function and completely missed the documentation. I'll fix this up next week.

**Comment by maxmantei** [comment]
No worries, thanks for adding the function! :)
