### ISSUE TITLE
Add docs for svd_U and svd_V

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/docs#309]
#### Summary:

These signatures are now supported:
```stan
matrix svd_U(matrix);
matrix svd_V(matrix);
```
and should be documented in functions signatures. 

I unfortunately added and merged those in stanc3 and forgot on the rule of not merging non-documented functions. If this isnt documented we will need to remove those from stanc3. Lets try to avoid that :)

Anyone up for adding those? See https://github.com/stan-dev/docs/pull/305 for an example of a docs PR for a similar signature.

cc: @dashadower @bbbales2

**Comment by bbbales2** [comment]
Whoops, yeah I was gonna do it after the stanc3. Sure thing, I'll put a pull up later today
