### ISSUE TITLE
Generating 2.26 web docs for RC

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/docs#315]
#### Summary:

@serban-nicusor-toptal Would it be possible to generate the html for 2.26 at the time of release candidate (which should be tomorrow morning CET time)? I think that would make it easier to link to docs for new features.

#### Current Version:
v2.18.0

**Comment by serban-nicusor-toptal** [comment]
Hey @rok-cesnovar sorry it took a bit longer but `R` updated so I had to re-compile all packages used in docs for `gelman-linux`.
You can find the [PR for docs](https://github.com/stan-dev/docs/pull/316) and [PR for stan-dev.github.io](https://github.com/stan-dev/stan-dev.github.io/pull/139). 
I'm following [this](https://github.com/stan-dev/cmdstan/issues/957) issue so I'll get done everything tomorrow morning before US wakes up.
If there's anything else I can help with please let me know !

**Comment by rok-cesnovar** [comment]
Nice, thanks!
