### ISSUE TITLE
Update models to stanc3 synatx

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/docs#330]
#### Summary:

Example: https://mc-stan.org/docs/2_26/stan-users-guide/QR-reparameterization-section.html

The transformed data could be rewritten from
```stan
transformed data {
  matrix[N, K] Q_ast;
  matrix[K, K] R_ast;
  matrix[K, K] R_ast_inverse;
  // thin and scale the QR decomposition
  Q_ast = qr_thin_Q(x) * sqrt(N - 1);
  R_ast = qr_thin_R(x) / sqrt(N - 1);
  R_ast_inverse = inverse(R_ast);
}
```

to

```stan
transformed data {
  // thin and scale the QR decomposition
  matrix[N, K] Q_ast = qr_thin_Q(x) * sqrt(N - 1);
  matrix[K, K] R_ast = qr_thin_R(x) / sqrt(N - 1);
  matrix[K, K] R_ast_inverse = inverse(R_ast);
}
```
So removing deprecated syntax and use shorter and cleaner sytnax where possible.

Essentialy what @andrjohns did in https://github.com/stan-dev/example-models/pull/190.

This is a good issue for anyone looking to contribute but doesnt know where to start.

**Comment by caesoma** [comment]
Is this just replacing the separate type specification with the full specification and assignment for the example models in this `Part 1`?

**Comment by rok-cesnovar** [comment]
Yes, mostly replacing separate declaration and assignment to a one-liner. I was aiming to get this fixed wherever we do this user guide but fixing it in any chapter would be more than welcome!
