### ISSUE TITLE
Vectors with varying bounds is out of date and tells users that this can be a single type

### ISSUE THREAD

**Issue by spinkney** [stan-dev/docs#338]
Varying upper and lower bounds are allowed since CmdStan 2.24 (see https://github.com/stan-dev/stanc3/pull/552). The places where this needs to be fixed are

https://mc-stan.org/docs/2_26/stan-users-guide/vectors-with-varying-bounds.html

Also it is useful to have a section on vector bounds in

https://mc-stan.org/docs/2_26/reference-manual/univariate-data-types-and-variable-declarations.html

Other relevant recent discussions
Discourse discussions on [array bounds](https://discourse.mc-stan.org/t/array-bounds/20767/3) and [varying upper bound without lower bound](https://discourse.mc-stan.org/t/varying-upper-bound-without-lower-bound/19128/2?u=spinkney).

**Comment by rok-cesnovar** [comment]
@spinkney Do we just remove 21.4 then to address the first part of this issue?

**Comment by spinkney** [comment]
I think it's useful but can be rewritten. Where we state that varying bounds can be declared like in the following examples. We give examples. Then say that this is equivalent to writing out like so (which is what is currently in the manual).

**Comment by rok-cesnovar** [comment]
Ok, yeah, that makes sense! Thanks.
