### ISSUE TITLE
Broken reference in Gaussian process section of users guide

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/docs#34]
#### Summary:
The hyperlink to the section Priors for Gaussian Process Parameters in the users guide for 2.18 is not working.

#### Description:
Search for "Priors for Gaussian Process Parameters {#priors-gp.section}" and you will see the problem. I think this is only a problem in the html version.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by mitzimorris** [comment]
moved this to issue for all manual-related fixes -  https://github.com/stan-dev/docs/issues/15
