### ISSUE TITLE
Handling Binary Groups in MRP docs

### ISSUE THREAD

**Issue by adamConnerSax** [stan-dev/docs#343]
In https://mc-stan.org/docs/2_26/stan-users-guide/coding-mrp-in-stan.html#coding-binary-groups

I think the example stuff might need a "to_vector" (or something?) around the ```{epsilon, -epsilon}[sex]``` term in the vectorized model expression. Otherwise, at least when I try, I get a compiler error about the types given to "+" when I add the scalar (real) alpha. Adding ```to_vector``` fixes this.

**Comment by bbbales2** [comment]
@adamConnerSax opened up a pull request to fix this. Lemme know if this looks good to you: https://github.com/stan-dev/docs/pull/346
