### ISSUE TITLE
Does the ODE section of the users guide need updated with new form?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/docs#349]
#### Summary:

Looking at the ODE guide, should this be updated to use the new variadic form?

https://mc-stan.org/docs/2_19/stan-users-guide/coding-an-ode-system.html

#### Current Version:
v2.18.0

**Comment by rok-cesnovar** [comment]
You are looking at the old docs: https://mc-stan.org/docs/2_26/stan-users-guide/coding-the-ode-system-function.html
