### ISSUE TITLE
No index for Stan Functions Reference

### ISSUE THREAD

**Issue by robert-dodier** [stan-dev/docs#367]
I'm looking at the Stan Functions Reference (https://mc-stan.org/docs/2_26/functions-reference/index.html) and it appears there is no index. Just to be clear, I mean a list of the names of all the functions with links to their descriptions. I see the search box, but I was hoping to find an index; the search box doesn't function the same way. I'd like to recommend that an index be generated and linked from the front page.

There is an existing issue, #14, which is titled "No index page at mc-stan.org/docs", but that is about index.html and not an index in the sense of a list of items.

**Comment by bob-carpenter** [comment]
I agree that'd be really helpful.  The only reason we don't have one is that we don't know how to generate one in HTML from the R markdown source.  The [R markdown doc](https://bookdown.org/yihui/bookdown/latex-index.html) says:

> Currently the index is only supported for LaTeX/PDF output.

Suggestions for how to get around this issue are very welcome.

Our pdf output does have an index.  We even use the index it generates for auto-completion in editor interfaces.

**Comment by mitzimorris** [comment]
there's a python script:  https://github.com/stan-dev/docs/blob/master/extract_function_sigs.py
that's used by the RStudio folks to get all the function sigs and descriptions.

**Comment by mitzimorris** [comment]
we might be able to program something up - https://stackoverflow.com/questions/65639306/how-to-add-a-alphabetical-index-with-pandoc/65656823#65656823

**Comment by WardBrian** [comment]
happy to spend a day next week trying anyway - both Steve and Bob have requested this in the web version
