### ISSUE TITLE
need index entries for each function for a distribution, e.g. pdf, cdf, ccdf, etc.

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#37]
#### Summary:
The Stan Functions Reference index should index all functions for a distribution - e.g.

```
bernoulli;~;real;92
bernoulli_cdf;(ints y, reals theta);real;92
bernoulli_lccdf;(ints y | reals theta);real;92
bernoulli_lcdf;(ints y | reals theta);real;92
```
currently entries for `_cdf` et al. are missing.

#### Description:
Conversion from latex to Rmd garbled functions reference index entries for latex manual - index entry in HTML comment is correct, latex entry is missing suffix:

```
<!-- real; bernoulli_lpmf; (ints y | reals theta); -->
\index{{\tt \bfseries bernoulli}!{\tt (ints y | reals theta): real}|hyperpage}
```
should be:

```
<!-- real; bernoulli_lpmf; (ints y | reals theta); -->
\index{{\tt \bfseries bernoulli\_lpmf}!{\tt (ints y | reals theta): real}|hyperpage}
```

#### Current Version:
v2.19.0

**Comment by bgoodri** [comment]
Also, the page numbers are wrong in the PDF index.

**Comment by mitzimorris** [comment]
fixed all issues, uploaded correct tgz and zip for functions reference to release.
