### ISSUE TITLE
CmdStan: New command line option in 2.27 is not documented

### ISSUE THREAD

**Issue by jgabry** [stan-dev/docs#372]
I may just be missing it but I can't find any doc for the new `-- info` option for stanc3. I was expecting to find it in 

https://mc-stan.org/docs/2_27/cmdstan-guide/stanc.html#command-line-options-for-stanc3

Am I overlooking it somewhere?

**Comment by rok-cesnovar** [comment]
It is missing yes abd should be documented with the rest of the stanc arguments.

**Comment by mitzimorris** [comment]
is there a way to add some kind of checkbox on stanc3 PRs to flag things which should be documented in the online docs?

**Comment by jgabry** [comment]
> is there a way to add some kind of checkbox on stanc3 PRs to flag things which should be documented in the online docs?

That would be nice!
