### ISSUE TITLE
add complex number doc to functions reference, reference manual, and user's guide

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/docs#375]
#### Summary:

See title.

#### Description:

We need:

* _reference manual_: type system, constructors/accessors, and assignment/promotion rules
* _functions reference_: all the C++ standard library functions plus the basic constructors/access need doc here
* _user's guide_: simple use case, probably just a complex regression at this point as we won't have vector or matrix types in the first release

#### Additional Information:

This shouldn't get merged until complex numbers are merged in the `stanc3`, `stan`, and `math` repos.

#### Current Version:
v2.18.0

**Comment by WardBrian** [comment]
Closed by #378
