### ISSUE TITLE
docs aren't using packages `arm`, `rstan`, or `bayesplot` - cleanup accordingly

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#377]
#### Summary:

Clean up Stan User's Guide, removing Stan programs that are now part of the Stan Workflow book,
including directory `stan` which has a bunch of Stan programs, and remove dependencies on
R packages `arm`, `rstan`, and `bayesplot`.

Improve user install instructions.

#### Description:

We need to make it easier for contributors to the docs repo to be able to build and check their work locally.
There are many places in the docs where there's raw latex; presumably because of mathjax formulas in the Rmd files
which don't render properly.    If both developers and reviewers can easily build the docs, it will make it easier to catch these kinds of errors before they go into the docs.

#### Additional Information:

Building the pdf version of the docs introduces more complexity, as the user needs to have the latex toolchain installed as well.  The pdf uses the Lucida fonts, and installing these fonts is quite challenging, at least on MacOs.

**Comment by WardBrian** [comment]
Covered in #390
