### ISSUE TITLE
Reference Manual: Multiple delclarations not documented

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/docs#379]
#### Summary:

Multiple declarations should be documented in the reference manual and user's guide.

#### Description:

PR https://github.com/stan-dev/stanc3/pull/670 added the ability to write declarations like 

```
real x, y;
```

Not only is this feature useful and should be shown off, there are also some questions or edge cases it would be good to document up front. For example, the PR shows you can do assignment at the same time, but can you do constraints, etc?  Also, is the full form (without constraints) available for local variables?

* [x] add documentation to section 5 of reference manual, "Data Types and Declarations" covering boundary conditions
* [ ] extend BNF grammar for language to include the syntax
* [ ] add explanation and example use case to user's guide

I would be happy to write it up if @rybern could give a brief overview of what is or isn't supported

**Comment by bob-carpenter** [comment]
This issue should include should also be mentioned and shown by example in the user's guide somewhere.  That can go in the same 

I take it the question is whether this is the full form for block variables and whether the same form is allowed without constraints for local variables.

```
constrained type v1 = e1, v2 = e2, ..., vN = eN;
```

I updated the issue to reflect that the user's guide should also be updated.  I'm happy to review the doc changes or help write them.

**Comment by WardBrian** [comment]
I've done some tests and it seems like all declarations are just turned into the un-sugared form. e.g, 

```stan
data {
  int<lower = 0> N,D;
  vector[N] x, y;
  array[3,2] matrix[4,4] a, b;
}

generated quantities {
  real z = 1, w = 2;
  for(i in 1:N){
    int j = i + 1, k = i + 2;
  }
}
```
gets turned into 
```stan
data {
  int<lower=0> N;
  int<lower=0> D;
  vector[N] x;
  vector[N] y;
  array[3, 2] matrix[4, 4] a;
  array[3, 2] matrix[4, 4] b;
}
generated quantities {
  real z = 1;
  real w = 2;
  for (i in 1 : N) {
    int j = i + 1;
    int k = i + 2;
  }
}
```
meaning that constraints etc all just get copied along. 

I think that's all I need to know to write the doc
