### ISSUE TITLE
revise variable typing in all doc

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/docs#383]
#### Summary:

Include table describing variable type in user's guide to manual and upgrade all doc to include `offset` and `multiplier` and use new array syntax.

#### Description:

* [x] Describe variable types in reference manual.  Copy [table from user's guide](https://mc-stan.org/docs/2_27/stan-users-guide/basic-functions-section.html#type-declarations-for-functions) to reference manual.
    * block variable: constrained, sized
    * local variable: unconstrained, sized
    * function argument: unconstrained, unsized

* [x] Update all doc to use `array[N] T x` in place of `T x[N]`
* [x] include deprecation notice for `T x[N]` in reference manual.
* [x] update Stan program style guide in user's guide

#### Current Version:
v2.26.0

**Comment by WardBrian** [comment]
First step of this is making sure the style guide actually represents what we want it to, I'm happy to then comb through and make sure everything looks good
