### ISSUE TITLE
broken link to csr.html in sparse-matrices.html: should be CSR.html

### ISSUE THREAD

**Issue by arabidopsis** [stan-dev/docs#39]
#### Summary:
HTML link incorrect

#### Description:
link in sparse-matrices.html to csr.html should be CSR.html

#### Additional Information:
Problem is probably due to developing on a case preserving filesystem (mac, windows)
but deploying on a case sensitive filesystem (linux)

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
Thanks for reporting.  We'll fix it.

**Comment by mcol** [comment]
This can be closed now.
