### ISSUE TITLE
Equations in ODE section followed by "id:  " tag

### ISSUE THREAD

**Issue by mespe** [stan-dev/docs#40]
#### Summary:

"id: " tags are printed in PDF of User Guide v2.19, ODE section

#### Description:

In the Users manual section 13 (ODEs), the equation blocks are followed by the printed tags, e.g. "id:ode-sho.equation" (p168), "id:ode.linODEs" (p170), etc.

#### Current Version:

v2.19.0

**Comment by mcol** [comment]
There are a number of these also in other sections. I'm not sure if and how they are used, they appear to be non functional (perhaps a leftover from some older way of generating these documents?).

**Comment by rok-cesnovar** [comment]
This was resolved at some point in the 2 years since this was opened.
