### ISSUE TITLE
Forward function declarations are not needed for simple recursion

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/docs#408]
#### Summary:

In the reference manual, both [here](https://mc-stan.org/docs/2_27/reference-manual/function-definition-block.html) and [here](https://mc-stan.org/docs/2_27/reference-manual/forward-declarations-section.html#recursive-functions) it is stated that a forward declaration is needed for recursion. This is not true in stanc3 -- function signatures are [added](https://github.com/stan-dev/stanc3/blob/eeb5e3974167a52b0396fd3ad9ec4f2e8e324c56/src/frontend/Semantic_check.ml#L1741-L1743) to the symbol table before the [body is checked](https://github.com/stan-dev/stanc3/blob/eeb5e3974167a52b0396fd3ad9ec4f2e8e324c56/src/frontend/Semantic_check.ml#L1785), so they are optional unless you need complicated mutual recursion or are defining an external function.

This can be verified by compiling the fibonacci example with and without the forward declaration.

#### Current Version:
v2.27.0

**Comment by bob-carpenter** [comment]
Nice!  The only reason the forward declarations were in there is that I couldn't figure out how to include them on the fly using the Spirit Qi parser because of the way I had scoped semantic actions.

**Comment by bob-carpenter** [comment]
I don't recall Java requiring forward declarations for mutual recursion.   Isn't it just a matter of how long we wait before resolving function signature well formedness?

**Comment by WardBrian** [comment]
I suppose you could scan through once and treat each function as if it was a forward declaration, and then scan a second time and verify they are well-typed in their definitions (I think this is what let-and ends up doing), forward declarations just allow you to do it in a single typechecking pass.

**Comment by bob-carpenter** [comment]
I realize the constraints mean you can't resolve mutual recursion in a single pass without forward declarations.  I was trying to ask how they're resolved and if that would be possible for Stan.  It'd be nice to remove the recursion-oriented forward declarations altogether if possible.

**Comment by WardBrian** [comment]
I can't find anything explicitly describing how it is done in a language like Java, I'm just assuming they do this sort of preliminary pass. There's certainly no reason we couldn't do it in Stan if you'd like to add it to the wishlist next to function overloading

**Comment by WardBrian** [comment]
Actually, we already do a second pass over the functions block to make sure that all functions which were declared eventually received definitions. So we could definitely have another

**Comment by WardBrian** [comment]
Do we have some equivalent of this [vignette on external functions](https://statmodeling.stat.columbia.edu/2017/03/31/running-stan-external-c-code/) in the docs somewhere? It's worth noting that standalone declarations are useful for this context to whatever extent it is supported

**Comment by bob-carpenter** [comment]
1.  Not having to use forward declarations would be a great feature.  I don't know how many people use recursion, so not such a high priority.  But it'd make all the doc and descriptions of how to write functions cleaner.

2.  No, I don't think there's a general doc on how to hook up external functions.  There are some things in the doxygen doc and also on the wiki for stan-dev/stan.  Could you open a feature request to write such doc?  Our whole getting started as a developer doc could use another pass, too.

**Comment by WardBrian** [comment]
Created https://github.com/stan-dev/stanc3/issues/976 for the first bullet and  #410 for the second bullet.

**Comment by bob-carpenter** [comment]
Cool!  And thanks, @nhurre---I've been wanting to modify the way user-defined functions work to do this and allow overloading ever since they were introduced.
