### ISSUE TITLE
Minor error in Sec 2.1 of User's Guide

### ISSUE THREAD

**Issue by mdscheuerell** [stan-dev/docs#41]
#### Summary:
Sec 2.1 on Autoregressive models contains a minor error in the description of AR(1) models.

#### Description:
I had made a comment on the previous manual about an alternative parameterization for an AR(1) model with a non-zero mean (level). The current version of the manual has acknowledged that (thanks!), but there is a typo/error in [footnote 7](https://mc-stan.org/docs/2_18/stan-users-guide/autoregressive-section.html#fn7).

It currently reads,

> The intercept in this model is $\alpha / (1 - \beta)$. An alternative parameterization in terms of an intercept $\gamma$ suggested Mark Scheuerell on GitHub is $y_n \sim \text{normal}(\alpha + \gamma (x_{n-1} - \alpha), \sigma)$.

but it should read,

> The intercept in this model is $\alpha / (1 - \beta)$. An alternative parameterization in terms of an intercept $\gamma$ suggested Mark Scheuerell on GitHub is $y_n \sim \text{normal}(\gamma + \beta (x_{n-1} - \gamma), \sigma)$

#### Current Version:
v2.18.0

**Comment by mcol** [comment]
This can be closed.

**Comment by jgabry** [comment]
Closing, fixed by @mcol in #63
