### ISSUE TITLE
Stanc3 parser documentation - cross-reference, describe error and warnings syntax

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#411]
#### Summary:

For the CmdStanX interfaces, it would be convenient to have a description of
the Stanc3 compiler template (if any) used for warnings, syntax, and semantic error messages.
Where is the appropriate place to put this info?

#### Description:

In the docset, the parser is described in the CmdStan User's guide and the
language syntax is described in the Reference Manual, and the User's guide
has a section on the Stan program style.

**Comment by mitzimorris** [comment]
@bob-carpenter and @WardBrian - this should be up your alley.

**Comment by WardBrian** [comment]
IMO, the description of error messages should go in the cmdstan guide, as that is the only place in our doc we currently discuss the actual stanc3 compiler as opposed to the 'Stan abstract machine' of sorts (stealing a term from the C world). It should backlink to the pages on syntax and extra-grammatical constraints. 

Our current documentation of the type rules is pretty high-level and doesn't cover everything we check for in the compiler. For example, it doesn't mention that functions can't shadowing stan math functions (or really anything about the user defined functions), the fact that re-declaring the same variable is not allowed, or the locations where `target` is or is not accessible. I don't think it's useful to most people to try to write a full series of type judgements for the Stan language, but we could definitely discuss more of what we check.
