### ISSUE TITLE
add version provenance: (since [at least]) version x

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/docs#417]
#### Summary:

For the functions reference, add a provenance for each function indicating when it was introduced.   

#### Description:

This is especially important now that the interfaces are releasing asynchronously and users often have later doc than the version of Stan they're using.

#### Additional Information:

It will be OK to follow the Python docs and allow "since at least".

It would also be nice to add the same thing for language features, but it's less clear where to document them.  For example, the `complex` type was introduced recently, but types are described all over the doc.

There are lots of place this is listed: release notes, auto-generated function sigs, the actual stanc3 or previous stanc.

#### Current Version:
v2.28.0

**Comment by WardBrian** [comment]
So using `extract_function_signatures.py` I've generated a list of all the current function signatures alongside the first time they were extracted.

Here it is:
https://gist.github.com/WardBrian/74227d7062c4ecc8a9b6ff9d68cf5dde

This list is sorted by the order they appear in the .Rmd files. Getting this information back into the docs is non-trivial in effort, but definitely doable.

@rok-cesnovar - do you know of any other exceptions to the rule? skew_double_* do indeed appear as 2.27 on this list.

**Comment by WardBrian** [comment]
I think it’s fine to miss late, missing early is the problem. Saying something has been available since at least 2.23, when in reality it’s been in since forever, is probably okay as long as we don’t go in the other direction. 

For things like the ODE solvers, changing signatures would count as “adding” new in my script, which I think is how we want it to be treated in general

**Comment by rok-cesnovar** [comment]
This is just a fix, it always required that to compile to C++, stanc3 just did not enforce it until 2.27y

**Comment by WardBrian** [comment]
I considered trying to search through the old revisions of stan-dev/stan and find the functions from before 2.18, but it seems like the latex didn't have as consistent a format as the html does. So, until someone is much braver than me, 2.18 will be the furthest we can go back in history. Probably fine?

**Comment by WardBrian** [comment]
Does "First documented in version 2.5" sound okay or is that too specific to the way we're getting this information?
