### ISSUE TITLE
need html comments for all signatures for built-in functions

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#42]
#### Summary:
Conversion from latex to Rmd failed to register signatures some functions.  also missing entries for sampling statements for distributions.

#### Description:
Every function signature should have an accompanying HTML comment, e.g.:
```
<!-- real; min; (real[] x); -->
<!-- int; min; (int[] x); -->
```

Comparison to info scraped from latex index indicates about 50 missing signatures - need to check out 2.18.1 release, run task `make manual`, and examine file `doc/stan-functions-2.18.1.txt`

#### Current Version:
v2.19.0

**Comment by bgoodri** [comment]
Also, `binomia\_l` is missing an `l` in several places, such as
https://github.com/stan-dev/docs/blob/master/src/functions-reference/bounded_discrete_distributions.Rmd#L55

**Comment by mitzimorris** [comment]
@bgoodri - 53 missing entries are for sampling statements on distributions - 

when adding these back in, it would be possible to add info about params, e.g. instead of:

```
bernoulli;~;real;92
```

we could do:

```
<!-- real; bernoulli; ~ reals theta; -->
```

**Comment by mitzimorris** [comment]
just merged #43 - @bgoodri - now there are 724 entries in the form of HTML comments for all built-in functions, distributions, and sampling statements.
in 2.18.1, there were redundant entries for the "abs" function - should be 1, not 3 entries.

**Comment by bgoodri** [comment]
I have a local branch that makes stan-functions.txt using Python.

**Comment by mitzimorris** [comment]
who should we talk to at RStudio to clear this up?
@bgoodri - what do you do with the stan-functions.txt file?

**Comment by bgoodri** [comment]
I just convert it to a lookup table, stick it into rstan's namespace, and
RStudio calls it.

**Comment by mitzimorris** [comment]
sounds good - how about checking that python script into docs? what's a good name -  'list_stan_function' or similar?

**Comment by bgoodri** [comment]
https://github.com/stan-dev/docs/pull/128/
