### ISSUE TITLE
Docs on complex numbers use non-existent to_real, to_imag

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/docs#438]
#### Summary:

The guide here https://mc-stan.org/docs/2_28/stan-users-guide/complex-linear-regression.html uses `to_real()`, `to_imag()` in the examples. 

As far as I understand think those functions are actually `get_real()`, `get_imag()`?

#### Current Version:
v2.18.0

**Comment by WardBrian** [comment]
>those functions are actually get_real(), get_imag()

Correct
