### ISSUE TITLE
Typo in volatility model sampling distribution

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/docs#44]
#### Summary:
Equation for sampling distribution of `h_t` has a typo.

#### Description:
Both the RHS and LHS of recurrence equation
https://github.com/stan-dev/docs/blob/bd1efaeda754a38380d4d9eca00276982c0202ea/src/stan-users-guide/time-series.Rmd#L519

use h_<sub>t</sub>. RHS should be using h_<sub>t-1</sub>

#### Current Version:
v2.18.0

**Comment by jgabry** [comment]
thanks, fixed by @mcol in #62
