### ISSUE TITLE
Add a custom 404 page with helpful links

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/docs#451]
#### Summary:

The docs 404 page could be a bit more helpful. Currently its just the defautl Github Pages 404 error page

![image](https://user-images.githubusercontent.com/28476796/145582142-897bcbe8-2b4a-4883-99d0-19661cc2e926.png)

Following these steps https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site we could instead create a simple page with links to the user manual, language reference and functions reference?

#### Current Version:
v2.28.0

**Comment by mitzimorris** [comment]
is there a top-level index.html page?

**Comment by mitzimorris** [comment]
there's also this:  https://github.com/stan-dev/stan-dev.github.io/blob/master/404.md

**Comment by rok-cesnovar** [comment]
Yeah, that one is triggered at the top level, when calling for example: https://mc-stan.org/foo

https://mc-stan.org/docs/foo leads us to the page I pasted above, because /docs is routed to this repo I guess.

**Comment by WardBrian** [comment]
You can view the page bookdown generates for this by manually navigating to https://mc-stan.org/docs/2_28/stan-users-guide/404.html for example. It would be great if github was smart enough to use these
