### ISSUE TITLE
ESS Computation Wrong (only in docs)

### ISSUE THREAD

**Issue by roualdes** [stan-dev/docs#46]
#### Summary:
Both

https://mc-stan.org/docs/2_18/reference-manual/effective-sample-size-section.html

and

https://mc-stan.org/docs/2_19/reference-manual/effective-sample-size-section.html

have an incorrect mathematical manipulation with respect to rho_t.

#### Description:
Taken from https://github.com/stan-dev/stan/issues/2762, 

"""
I am confident the implementation in Stan is correct, this issue is only about the documentation.

The issue is with the claim that the autocorrelation integral term (t-mean)(s-mean) simplifies to ts, but it actually simplifies to ts - mean^2, and the derivation in Section 15.4.1 ommits the squared mean.

The correct simplified autocorrelation equation should read
"""

`\rho_t = \frac{1}{\sigma^2} \int_{\Theta} \theta^{(n)} \theta^{(n+t)} p(\theta) d\theta - \frac{\mu^2}{\sigma^2}`.

#### Current Version:
v2.19.0

**Comment by jgabry** [comment]
Thanks, fixed by @mcol in #74
