### ISSUE TITLE
Cmdstan/ADVI/Configuration - less than used instead of greater than

### ISSUE THREAD

**Issue by stephensrmmartin** [stan-dev/docs#460]
#### Summary:

Where < is used, > should be used.

E.g., "Must be < 0. Default is 100."

#### Description:
![image](https://user-images.githubusercontent.com/2332684/148311659-2a5a8c1d-5d05-43f1-aa76-7ad10ef6f3f9.png)

See image above.

#### Current Version:
2_28

**Comment by WardBrian** [comment]
This was fixed in #454, but the docs won’t be re built to reflect until 2.29 at the end of the month
