### ISSUE TITLE
syntax highlighting for code fragments

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#463]
#### Summary:

Use the highlights.js library  for Stan code in the Stan User's Guide.

#### Description:

Stan highlighting has been updated recently - lets add this to the Stan User's Guide.
For the HTML, this requires more config and proper stylesheets.

Investigate which manuals need this - if they don't contain extended code fragments, the
impelmentation and maintenance burden aren't worth it.

Investigate ways to get styling into pdfs - can this be done w/out having to add
more latex tags into all the Rmd files?

#### Additional Information:
announcement here:  https://discourse.mc-stan.org/t/stan-the-gathering-jan-13-11am-est/24944/9

#### Current Version:
v2.29.0

**Comment by mitzimorris** [comment]
here's an example of using highlights.js in conjunction with line numbering - the color choices are tweaked for Tufte-format documents
<img width="877" alt="Untitled" src="https://user-images.githubusercontent.com/5466612/148694349-5c1c5182-e3b3-4559-a118-19231a519bba.png">

**Comment by WardBrian** [comment]
We also just had Stan added to skylighter, the Haskell library which is used by pandoc. I believe once pandoc has its next release, Bookdown can natively support Stan.

If we can make it supported sooner than that, it would be great, since I’m not sure what the release cycle looks like over there

**Comment by mitzimorris** [comment]
hacked what's needed into bookdown here:  https://github.com/stan-dev/docs/tree/feature/463-syntax-highlighting

to add highlighting to pdfs would require adding latex tags around all codeblocks in the .Rmd files, similar to the way that the functions ref has latex tags around function defs.

**Comment by mitzimorris** [comment]
bookdown and highlighting is messed up - cf https://github.com/rstudio/bookdown/issues/1053#issuecomment-820763401

**Comment by WardBrian** [comment]
This is actually easy using pandoc before it updates, I just didn't read the final paragraph [here](https://disco.uv.es/disco_docs/wikibase/doc/cat/pandoc_manual_2.7.3.wiki?174)

> If you are not satisfied with the built-in highlighting, or you want highlight a language that isn't supported, you can use the --syntax-definition option to load a KDE-style XML syntax definition file. Before writing your own, have a look at KDE's repository of syntax definitions.

It "just works" by adding one line to the output.yml file for each document

![image](https://user-images.githubusercontent.com/31640292/148785506-4687e303-7d10-4fc5-a1fc-b801a24e79d6.png)


I'll submit a PR shortly which does this
