### ISSUE TITLE
redirects broken because bookdown changed generated filenames

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#476]
#### Summary:
Between 2.27 and 2.28, generated file names seem to have changed - not sure why - but this is messing up the redirects.
see screenshot of what's in the repo below.

when using Google to locate something in the Stan docs, e.g. Stan language "include" syntax - Google usually comes up with very old version - https://mc-stan.org/docs/2_18/reference-manual/includes-section.html.   The redirects only get you to 2.27, not 2.28, because now the name has changed.

#### Description:
<img width="1620" alt="Untitled" src="https://user-images.githubusercontent.com/5466612/150696972-cb580237-121e-4350-abfb-8e64233d6d13.png">

#### Additional Information:
Is there a way to tell Google which paths to prioritize?  I remember plugging something in a long time ago - fuzzy on details.

#### Current Version:
v2.18.0

**Comment by WardBrian** [comment]
We manually fixed a bunch of these in #424, but I think only for the users guide? I’m not sure we realized there were more

I believe bookdown changed its page name generating algorithm before the 0.22 release, which led to this

**Comment by mitzimorris** [comment]
> Is there a way to tell Google which paths to prioritize? I remember plugging something in a long time ago - fuzzy on details.

remembered - this is on the stan-dev github pages - https://raw.githubusercontent.com/stan-dev/stan-dev.github.io/master/search/search.md

```
<div class="gcse-searchbox">
</div>

<div>
  <div class="gcse-searchresults"></div>
</div>
```

that's this:  https://developers.google.com/custom-search/docs/element
no longer remember anything about the account details....

**Comment by mitzimorris** [comment]
kinda mind-boggling that bookdown would do this - for any online book which is used and continually updated, links will break.  don't these guys know how the web works?

**Comment by WardBrian** [comment]
Well, if your links are all _also_ generated by bookdown (e.g, you use their style of links like `[Section Header]`), I think it would all be fine, which might be how it was justified.

I think our case of storing many of the same copy of a generated document and trying to link across them is probably pretty rare. I suppose if we wanted to 100% avoid this we could use git to check out and re-build all the older docs each time? Though I have no idea what that does to google results, and it is certainly way more effort than adding some redirects manually.

 I can't remember from my digging at the time, but it's also possible this was unintentional - the release notes never mentioned it explicitly, though where were some other changes done to name generation/resolution around that time as parts of new features or bug fixes

**Comment by mitzimorris** [comment]
I mean a link in an external document.
