### ISSUE TITLE
gp_ functions exposed but not documented

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/docs#478]
#### Summary:
The GP Covariance functions have multiple signatures exposed, but none are listed in the documentation. These functions are:

- `gp_dot_prod_cov`
- `gp_exp_quad_cov`
- `gp_matern32_cov`
- `gp_matern52_cov`
- `gp_exponential_cov`
- `gp_periodic_cov`

#### Current Version:
v2.18.0

**Comment by WardBrian** [comment]
I think these were documented in #272? But it might have been after the last time the docs got built

**Comment by andrjohns** [comment]
Ah right you are, thanks!
