### ISSUE TITLE
Missing Doc on 1D Integrator

### ISSUE THREAD

**Issue by jformaggio** [stan-dev/docs#48]
#### Summary:
1D Integrator: No documentation

#### Description:
It is my understanding that the 1D integrator is now part of version 2.18/2.19.  However, the documentation for use is not in the manual (at least for the 2.19 version).

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
Thanks.  We'll add the doc before the next release.

**Comment by mitzimorris** [comment]
cf discussion here:  https://discourse.mc-stan.org/t/how-to-use-integrate-1d/9218/11

**Comment by mitzimorris** [comment]
tracked down section in latex that got lost during conversion to bookdown in Aug/Sept 2018.
added section to chapter "Higher Order Functions" -
https://mc-stan.org/docs/2_19/functions-reference/functions-1d-integrator.html

**Comment by mitzimorris** [comment]
updated 2_19 html and pdfs - docs are online.

**Comment by yanivabir** [comment]
Thanks for fixing this!

In the "[precision loss](https://mc-stan.org/docs/2_19/functions-reference/functions-1d-integrator.html#precision-loss)" section of the integrate_1d function, there is reference to an example in the user guide of how to mitigate precision loss.

I cannot seem to find it: Not any reference to integrate_1d, nor in any of the documentation relating to ODEs or algebra solver. Searching for precision loss doesn't help either. I can't find an example in the arithmetic precision section of the guide either.

Does this example exist? Maybe it also got lost?

**Comment by bbbales2** [comment]
That advice is coming from here: https://www.boost.org/doc/libs/1_70_0/libs/math/doc/html/math_toolkit/double_exponential/de_tanh_sinh_2_arg.html

So if you have terms that look like (integral_endpoint - x), you can replace them with xc.

**Comment by bbbales2** [comment]
(Also thanks for pointing that out, yeah, musta gotten lost as well)

**Comment by bbbales2** [comment]
@mitzimorris I think the latest version of that example code for the user's guide is here: https://github.com/stan-dev/stan/commit/4a0595ada6a6b2f99841e6cdf1c551fb32a284b8

**Comment by mitzimorris** [comment]
@bbbales2  restored your fabulous prose to its rightful place:
https://mc-stan.org/docs/2_19/stan-users-guide/integrate-1d.html

**Comment by shoshievass** [comment]
I was just using this and there still isn't any mention of the tolerance argument in the docs (e.g. here https://mc-stan.org/docs/2_21/stan-users-guide/calling-the-integrator.html). 

I had the same parser issue discussed here: https://discourse.mc-stan.org/t/how-to-use-integrate-1d/9218/17

**Comment by mitzimorris** [comment]
@bbbales2 - tolerance argument guidance?

**Comment by bbbales2** [comment]
I guess in the best case we'd change the 2.21 docs that are posted to indicate that the tolerance is required (and specify a default of like 1e-8). Is there any mechanism of changing the release docs? Or does this just wait until 2.22?

**Comment by bbbales2** [comment]
And by "Or does this just wait until 2.22" I guess what I mean is, do changes to the online docs wait until the next release?

**Comment by bob-carpenter** [comment]
Changes to online docs should wait until they're valid for the most recent release.

**Comment by mitzimorris** [comment]
> I guess in the best case we'd change the 2.21 docs that are posted to indicate that the tolerance is required (and specify a default of like 1e-8)

sure, 2.21 docs are unversioned - if this is valid for 2.21, we can update and republish.
is this something that should be in the 2.21 docs?

**Comment by mitzimorris** [comment]
@bbbales2 - is there something further that needs to be done here?

**Comment by bbbales2** [comment]
We gotta add the tolerance-free version of the docs back after the next release (assuming the tolerance-free version works then)

**Comment by mitzimorris** [comment]
tolerance free will work in 2.22?
in which case, will add back in before generating release docs.
