### ISSUE TITLE
Wrong list of supported normal_id_glm

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/docs#503]
#### Summary:

Reported by @avehtari in https://github.com/stan-dev/stanc3/issues/1143

The normal_id_glm_lpdf function signature docs are unfortunately still wrong, even after my obviously failed attempt to fix this in https://github.com/stan-dev/docs/pull/457

The supported signatures at this point are:
```stan
normal_id_glm_lpdf(real, matrix, real, vector, real) => real
normal_id_glm_lpdf(real, matrix, real, vector, vector) => real
normal_id_glm_lpdf(real, matrix, vector, vector, real) => real
normal_id_glm_lpdf(real, matrix, vector, vector, vector) => real
normal_id_glm_lpdf(vector, row_vector, real, vector, real) => real
normal_id_glm_lpdf(vector, row_vector, real, vector, vector) => real
normal_id_glm_lpdf(vector, row_vector, vector, vector, real) => real
normal_id_glm_lpdf(vector, row_vector, vector, vector, vector) => real
normal_id_glm_lpdf(vector, matrix, real, vector, real) => real
normal_id_glm_lpdf(vector, matrix, vector, vector, real) => real
```

there seems to be a 
```
normal_id_glm_lpdf(vector, matrix, real, vector, vector)
```
listed in the functions reference page, which is incorrect. Triple-check the rest as well.

**Comment by avehtari** [comment]
The doc has a logical list, but the implementation is missing two of the logical combinations
