### ISSUE TITLE
cmdstan docs describing diagnostic csv should make it clear that parameter values are on the unconstrained scale

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/docs#514]
The [docs](https://mc-stan.org/docs/2_29/cmdstan-guide/stan_csv.html#diagnostic-csv-output-file) fail to make explicit that the parameter-draw-value columns (i.e. the ones with neither `p_` nor `g_` prefix) represent values on their respective **unconstrained** scale. I eventually worked out that they are unconstrained (code below for posterity), but it would have saved me some time (and possibly future confusion for others) if the text 
> all model parameter estimates

was changed to
> all model parameter estimates (on the unconstrained scale)

Code I used to confirm they're unconstrained:
```r
library(tidyverse)
library(cmdstanr)

# express & compile the model
code = "
parameters{
	real mu ;
	real<lower=0> sigma ;
}
model{
	mu ~ std_normal() ;
	sigma ~ std_normal() ;
}
"
mod = cmdstan_model(write_stan_file(code))

#sample
post = mod$sample(
	data = NULL
	, chains = 1
	, save_latent_dynamics = T
)

#get the draws
(
	post$draws(format='df')
	%>% as_tibble()
	%>% rename_with(
		.cols = c(mu,sigma)
		, .fn = function(x){paste0('drawn_',x)}
	)
) ->
	draws

# sigma draws are lower bound at zero as expected
(
	draws
	%>% ggplot()
	+ geom_histogram(aes(x=drawn_sigma),bins=50)
	+ scale_x_continuous(limits=c(0,max(draws$drawn_sigma)))
)

#save & read the latent dynamics
(
	post$save_latent_dynamics_files(basename='dynamics',timestamp=F,random=F)
	%>% read_csv(comment='#')
) ->
	dynamics

# join draws and dynamics
(
	dynamics
	%>% mutate(.draw=1:n())
	%>% left_join(draws)
) ->
	draws_and_dynamics


# plot drawn_sigma against "sigma" from latent dynamics file
(
	draws_and_dynamics
	%>% ggplot()
	+ geom_point(
		mapping = aes(
			x = drawn_sigma
			, y = sigma
		)
	)
)

```

**Comment by bob-carpenter** [comment]
Sorry that wasn't clear.  I agree we should be more clear that all of this output is on the unconstrained scale, including the Hessian.  

If you want to make the PR, it's easy to do through the GitHub web site by just editing the .Rmd.  If not, I'm sure someone will get to it.
