### ISSUE TITLE
Typo in Stan User's Guide 2.29

### ISSUE THREAD

**Issue by devincaughey** [stan-dev/docs#522]
I believe there is a typo in the Stan code for one of the example models in Section 9.3 (https://mc-stan.org/docs/2_29/stan-users-guide/naive-bayes-classification-and-clustering.html), under "Estimation without category-labeled training data". The lines `categorical_lpmf(k \mid theta)` and `categorical_lpmf(w[n] \mid phi[k])` should presumably have `|` in place of `\mid`.

**Comment by bob-carpenter** [comment]
Thanks, @devincaughey.  You're right about the bug and the fix.

It's very easy to submit a PR for a doc patch by just editing in GitHub if you'd like to submit the fix.  If not, I'm sure we'll get to it soon.
