### ISSUE TITLE
Bug in multinomial distribution wrt to softmax^-1

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/docs#529]
This was reported on Twitter https://twitter.com/clamusgh/status/1526397666527064064

![image](https://user-images.githubusercontent.com/28476796/168774401-15118681-eccc-4964-9c50-d97e44cbf971.png)

**Comment by spinkney** [comment]
It is wrong but the solution is also wrong. The input are the log-probabilities. https://github.com/stan-dev/math/blob/a0511bed56353983aba20aa492f122b0f3ddf10e/stan/math/prim/prob/multinomial_logit_lpmf.hpp#L20

I believe it should be `log_softmax(\theta)`. Which implies that we should probably have a `log_softmax` function.

**Comment by bob-carpenter** [comment]
> Which implies that we should probably have a log_softmax function.

`log_softmax` is already in Stan; see https://mc-stan.org/docs/2_29/functions-reference/softmax.html
