### ISSUE TITLE
Proposal: New file/url hierarchy for versions

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/docs#532]
## Status quo:

Each version we do the following:

1. Build the docs, creating a new folder in this repo `docs/2_XX` for version 2.XX
2. Run `add_redirects.py` on the old docs to add the text at the top of the page warning that this is not the latest version. For a page like `docs/2_28/reference-manual/algorithms.html`, this link is to `docs/reference-manual/algorithms.html`
3. Edit the four top-level (e.g. non-versioned) folders to point their redirect pages to the latest version. E.g, [this change](https://github.com/stan-dev/docs/blame/master/docs/reference-manual/arithmetic-expressions.html) for every file in those folders.

This system has (imo) three disadvantages:
1. No obvious stable links. If we're referencing across documentation or we want to link to documentation from somewhere else, you need to copy the link you're viewing and remove the version from the URL to get the 'redirect' link for that page, which the above system  keeps pointing in the right direction* 
2. Fragile redirects. If a page is deleted or changes its name, the above redirect system will keep pointing to the most recent version that existed. E.g,  if you go to this link: https://mc-stan.org/docs/2_22/stan-users-guide/coding-an-ode-system.html from the 2.22 docs, the link at the top of the page will take you to the 2.23 docs. There is _another link on that page_ which will just take you _to the same place_.
3. No ability for search engines to properly index the documentation. Because the latest version is a moving target, you'll find Google and friends often link to some arbitrary version in the past. Googling "Stan max function" takes me to a version of the documentation from 2.18

## Proposed change:

Rather than storing the newest version of the documentation in `docs/2_XX`, store it directly in the unversioned folders in `/docs/`. The update procedure is then as follows:

1. Move the 4 unversioned folders in `docs/` to a new folder called `2_XY` where XY is the _previous_ version
2. Build the docs and store this latest version in `/docs` directly
3. Add redirects to the pages in `2_XY` which point to the top level.

This addresses all three of the above points:
1. If you are on the latest version of the docs, the url in your browser bar will point to the latest version a year from now and is safe to copy as it is.
2. The redirects no longer have two levels of indirection which allows for this looping behavior. In particular, if a page gets deleted in a new version of the docs, the 'go to the latest version' page will lead to a 404. I would argue this is better behavior if we make a nice 404 page which includes links to the home pages of the docs to proceed.
3. From the perspective of the outside internet, we now have a persistent documentation page. The content in it will change from version to version, but the URL would not.

This would be fairly easy to implement ahead of 2.30. The folder structure at that time would look like:

```shell
docs/
├── 2_18
...
├── 2_29
# rather than redirects, the following folders hold the actual content
├── cmdstan-guide
├── functions-reference
├── reference-manual
└── stan-users-guide

``` 

Pinging @mitzimorris and @rok-cesnovar for thoughts

**Comment by mitzimorris** [comment]
thanks for reasoning through this.  I think it makes sense.

**Comment by mitzimorris** [comment]
as long as the version is somewhere in the docs that's fine - this sounds great!

**Comment by WardBrian** [comment]
I think I've sorted out the basics needed to do this, it's only a change really to the Jenkinsfile and then a manual (one-time) update to the stan-dev.github.io docs page

You can see what it looks like for a dummy version here - https://brianward.dev/standev-docs/stan-users-guide/ ( identical to https://brianward.dev/standev-docs/2_99/stan-users-guide/)

The redirects for older versions won't send you to this version of course, since it is hosted on my github page and not the official one, but you can quickly confirm that the URLs match up.

Unfortunately, github pages still doesn't pick up on the individual 404 pages, so we will need to make a custom 404 page in `/docs` which works for all the different documents (see #451)
