### ISSUE TITLE
CmdStan Installation instructions - add more info on conda

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#553]
#### Summary:
Incorporate information added to CmdStanPy install instructions via https://github.com/stan-dev/cmdstanpy/pull/578
into CmdStan documentation.

#### Description:
Better installation instructions is an evergreen issue - (cf #268, #452).

Currently, CmdStan install instructions recommend using conda everywhere, but MacOS users have reported problems - https://github.com/stan-dev/cmdstanpy/issues/552, so we need a more nuanced discussion, and possibly more background on Conda.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by WardBrian** [comment]
Closed by #555
