### ISSUE TITLE
User's Guide discussion of thinning samples - mention anti-correlated draws?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#554]
#### Summary:

The  Stan User's Guide section on thinning samples - should it provide more guidance?
In particular, mention anti-correlated draws?
https://mc-stan.org/docs/reference-manual/effective-sample-size.html#thinning-samples

#### Current Version:
v2.29.2

**Comment by bob-carpenter** [comment]
Thanks for pointing that out.  I'll update the doc and point out that rho_t can be negative and then qualify the thinning section.
