### ISSUE TITLE
broken links for current version of docs

### ISSUE THREAD

**Issue by mjhajharia** [stan-dev/docs#558]
Reference manual header that should point to current version is broken.

Example: https://mc-stan.org/docs/2_18/reference-manual/effective-sample-size-section.html from here I am redirected to https://mc-stan.org/docs/reference-manual/effective-sample-size-section.html which is broken. I think this might be from the last PR merged

**Comment by WardBrian** [comment]
This is caused by bookdown changing their naming convention a few doc versions ago. The current page is https://mc-stan.org/docs/reference-manual/effective-sample-size.html (notice the lack of -section)

we previously had fixed this by manually creating redirects
