### ISSUE TITLE
Add `linspaced_array` in stan documentation

### ISSUE THREAD

**Issue by mjhajharia** [stan-dev/docs#567]
In Stan's reference manual, insert  simple documentation of the function and its type specifications. 

See: https://discourse.mc-stan.org/t/assign-sequence-to-integer-array/18111/4

Also, there's *_array, *_vector and *_row_vector

**Comment by WardBrian** [comment]
The exposed signatures are 

```
linspaced_array(int, real, real) => array[] real
linspaced_int_array(int, int, int) => array[] int
linspaced_row_vector(int, real, real) => row_vector
linspaced_vector(int, real, real) => vector
```

**Comment by WardBrian** [comment]
Documented here: https://mc-stan.org/docs/functions-reference/container-construction.html

**Comment by mjhajharia** [comment]
sorry i didn't update the docs current version and it didn't come up in the search. my bad, thanks though!
