### ISSUE TITLE
von_mises probability function return types

### ISSUE THREAD

**Issue by pboesu** [stan-dev/docs#574]
#### Summary:
The return type for all von_mises related Stan probability functions is given as `R` in the [documentation](https://mc-stan.org/docs/functions-reference/von-mises-distribution.html#stan-functions-49). This is inconsistent with their behaviour and the design principles for log probability functions.

#### Description:
The Stan Function Reference lists the return type for `von_mises_lpdf/lupdf/cdf/lcdf/lccdf` functions as `R` (which in my interpretation means the return type depends on the input argument dimensions, as outlined [here](https://mc-stan.org/docs/functions-reference/vectorization.html#return-type).)

This does not match their behaviour - all of these functions return a scalar `real` when used with CmdStan 2.30.1 / cmdstanr 0.5.2, regardless whether the inputs are scalars or vectors. It also is inconsistent with the design principles for log probability functions outlined [here](https://mc-stan.org/docs/functions-reference/vectorization.html#vectorization). (Arguably, the `_cdf` is not covered in the latter, but that's a separate issue).

#### Additional Information:
I'm happy to create a PR changing `R` to `real` in https://github.com/stan-dev/docs/blob/master/src/functions-reference/circular_distributions.Rmd, but as I have not contributed to Stan docs before I wanted to double check whether manually editing the .Rmd is ok, or whether there is some Roxygen-like automated templating for the function reference part of the documentation.

#### Current Version:
v2.30

**Comment by WardBrian** [comment]
Good catch! You are correct that all of these should just say `real`. I believe the only one which should stay `R` is the RNG function.

Manually editing the files is fine as long as you make sure to edit also the latex and html comment signatures
