### ISSUE TITLE
Unclear wording for compound declare-and-define of matrices

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/docs#577]
#### Summary:

A user mentioned on the forum that the doc for compound declare and define for matrices is a [little confusing](https://discourse.mc-stan.org/t/assigning-different-dimensions/28680):

> Any type may be assigned. For example,
matrix[3, 2] a = b;
declares a matrix variable a and assigns it to the value of b

This wording implies that `a` is assigned to `b`, rather than the other way around 

[link to doc code](https://github.com/stan-dev/docs/blob/63bc6063c0cb1d92f1b3c6b39a137e17eeec0c6e/src/reference-manual/types.Rmd#L1601)

#### Current Version:
v2.18.0

**Comment by bgall** [comment]
Looks like this was addressed in #580 and can be closed.
