### ISSUE TITLE
function reference: (11.1.2.1) Arguments to the algebraic solver section could be clearer

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/docs#585]
#### Summary:
The section "Arguments to the algebraic solver"  (11.1.2.1)  could be clearer.

#### Description:
It's not clear what is the difference between the arguments `rel_tol` and `function_tol`. In addition, it would be useful to have the default values of these arguments and `max_num_steps`.

#### Current Version:
Latest in https://mc-stan.org/docs/functions-reference/functions-algebraic-solver.html

**Comment by bob-carpenter** [comment]
Thanks for the suggestions, @bnicenboim.  We'll try to get to them before the next release.  Or if you want to submit a simple PR, it's very easy to just edit and submit right on GitHub.  I'm not entirely sure what the args are myself or I'd just do it right now.

**Comment by bob-carpenter** [comment]
@charlesm93:  Hi, Charles---do you know enough about the args to the algebraic solver to add the doc Bruno's requesting?  You can just edit doc directly in GitHub and create a PR, so it should only take a second.

**Comment by charlesm93** [comment]
yes, I'm on it.

**Comment by charlesm93** [comment]
It looks like the doc is pretty outdated. Algebraic solvers now admit variadic arguments, rather than the strict signature described here. So this needs to be updated too.

**Comment by charlesm93** [comment]
Ok -- the variadic arguments didn't make it to the stan language. But they're definitely there in the math library.

I'll fix the variadic arguments first and then update the doc.

**Comment by bob-carpenter** [comment]
Could you open an issue in the `stanc3` repo to add the variadic arguments?  Thanks.  Pinging @WardBrian who should be able to help.

**Comment by WardBrian** [comment]
If you can give me a description of the variadic form I can implement it in the language. We will need names for them that differ from the existing names though

**Comment by charlesm93** [comment]
I did some digging in stan-math. It looks like the code for variadic arguments is there but then the whole thing gets wrapped in a function with a strict signature. So the stan-math library needs to be updated first. Here are the issues

- https://github.com/stan-dev/math/issues/2818
- https://github.com/stan-dev/stanc3/issues/576

I only worked on the latest updates to the algebraic solver from a distance, so I also posted on the Stan Forum to see if someone knew why the algebra solver was left in the state it currently is in.

- https://discourse.mc-stan.org/t/recent-history-of-algebraic-solver/28992

**Comment by charlesm93** [comment]
I should be able to handle the `stan-math` and `stanc3` libraries. But I won't wait too long to ask for help!

**Comment by bob-carpenter** [comment]
You can also use git blame to figure out who modified it and then ask them directly.

**Comment by charlesm93** [comment]
Ok. We've updated the stan-math library and created a PR for stanc3. I trust we'll have the variadic arguments in the upcoming Stan release. And _now_, I can update the doc to describe the new signatures and clarify the points brought up by @bnicenboim
