### ISSUE TITLE
Allow intial time and time vector to be var ODE function

### ISSUE THREAD

**Issue by charlesm93** [stan-dev/docs#59]
#### Summary:
Update the manual to indicate initial time and time can now be passed as var in the ODE functions. See https://github.com/stan-dev/stan/issues/2757.

#### Current Version:
v2.18.0

**Comment by charlesm93** [comment]
Should the PR include the recompiled markdown files, or only changes to the sources files?

**Comment by wds15** [comment]
@bob-carpenter ? Ups... I already merged this. So if in addition to the source files the generated ones should have been updated, then that has not yet happened. My bad.

**Comment by wds15** [comment]
This got documented and is merged
