### ISSUE TITLE
add documentation for Pathfinder method

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#648]
#### Summary:
Document the Pathfinder algorithm and how to invoke it via CmdStan.

#### Description:

The Pathfinder algorithm should be (briefly) described in the Stan Reference Manual and the CmdStan Guide should document the calling structure and output files.

#### Additional Information:

Pathfinder algorithm in Stan repo spec'd here:  https://github.com/stan-dev/stan/issues/3119,  PR here: https://github.com/stan-dev/stan/pull/3123

CmdStan calling interface PR here: https://github.com/stan-dev/cmdstan/pull/1155

#### Current Version:
v2.32.0

**Comment by mitzimorris** [comment]
cf   https://github.com/stan-dev/stan/issues/3207

**Comment by mitzimorris** [comment]
question - @bob-carpenter

we need to describe the column headers in the pathfinder output.

```
lp_approx__,lp__,theta
-2.4973, -8.2951, 0.0811852
-0.87445, -7.06526, 0.160207
-0.812285, -7.07124, 0.35819
```

what is `lp_approx__` and `lp__` ?

reading pathfinder paper psuedo code - is `lp_approx__`  a draw from the draws from the ELBO-maximizing normal approximation?   and `lp__` is the LBFGS estimate (which uses a Taylor approximation)?

**Comment by bob-carpenter** [comment]
These **should** be:

* `lp_approx__`: log density in the approximating distribution.

* `lp__`: log density in the target distribution.
