### ISSUE TITLE
Error in formula for log Jacobian of xform in inverse wishart distribution, Cholesky parameterization

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/docs#654]
#### Summary:
A plus sign and a pair of enclosing parentheses are missing from the formula given for the log Jacobian term in the Stan Functions Reference.

#### Description:
Section 28.4, "Inverse Wishart distribution, Cholesky Parameterization", in subsection 28.4.1, "Probability density function," states that the term for the log of the determinant of the Jacobian matrix  is

$$ \log \left| J_{f^{-1}} \right| = K \log(2) \sum_{k=1}^K (K - k + 1) \log {L_{W_{k,\, k}}}. $$

The correct formula is

$$ \log \left| J_{f^{-1}} \right| = K \log(2) +  \sum_{k=1}^K (K - k + 1) \log {(L_W)_{k,\, k}}. $$

#### Additional Information:
The math library appears to implement the correct formula, so this is just a documentation problem.

#### Current Version:
v2.32

**Comment by jgabry** [comment]
Thanks! I think I got the correct one in this PR: https://github.com/stan-dev/docs/pull/658
