### ISSUE TITLE
Description lmultiply looks wrong

### ISSUE THREAD

**Issue by aakhmetz** [stan-dev/docs#659]
<img width="704" alt="Screenshot 2023-08-03 at 12 47 59 PM" src="https://github.com/stan-dev/docs/assets/2173206/c37a4298-1dbd-4c7b-aee3-b5b6edd5bfb4">

I don't think it is correct. I think the first line is true also for any y > 0. The second line should impose y > 0, because log of the negative value is undefined.

source: https://mc-stan.org/docs/functions-reference/composed-functions.html

**Comment by spinkney** [comment]
The function will return 0 if $y = 0$ in the first line (see below). The second line is incorrect because this will return `NaN` for $y < 0$. 

```cpp
template <typename T1, typename T2, require_all_arithmetic_t<T1, T2>* = nullptr>
inline [return_type_t<T1, T2>](https://mc-stan.org/math/group__type__trait_gacbaff683cd2683209e6855e2c7aaeffe.html#gacbaff683cd2683209e6855e2c7aaeffe) [lmultiply](https://mc-stan.org/math/namespacestan_1_1math_a70dc434e6485c32aac018c358c058f38.html#a70dc434e6485c32aac018c358c058f38)(const T1 a, const T2 b) {
  using std::log;
  if (a == 0 && b == 0) {
    return 0;
  }
  return a * log(b);
}
```

https://mc-stan.org/math/prim_2fun_2lmultiply_8hpp_source.html
