### ISSUE TITLE
Typo in name of function for gaussian regression (is ..._lpmf, should be ..._lpdf)

### ISSUE THREAD

**Issue by gbiele** [stan-dev/docs#67]
#### Summary:
There is a small  typo in section 15.2 Normal-Id Generalised Linear Model (Linear Regression) of the Stan function reference. The (wrong) function name does not exist as a function in Stan/math.

#### Description:
In section "15.2.3 Stan Functions" the Stan function for the Gausssian regression model  is called 'normal_id_glm_lpmf', but it should be 'normal_id_glm_lpdf'.

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
Thanks.  We'll fix it.

The file in question to edit is: `docs/src/functions-reference/unbounded_continuous_distributions.Rmd`

**Comment by avehtari** [comment]
This has been previously reported in https://github.com/stan-dev/docs/issues/36#issuecomment-493591288

**Comment by mitzimorris** [comment]
fixed as part of #36
