### ISSUE TITLE
latex display mode in Rmd vs quarto

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#686]
#### Summary:

The .Rmd files use latex display mode syntax for equations and set of equations - investigate how to make these render properly using quarto.

#### Description:

We plan to migrate from bookdown to quarto.
Although quarto can render .Rmd files, the latex display mode syntax `\[ ... \]` doesn't render properly.
The alternative is `$$ ... $$`, which changes the size and layout of summation and integral signs.

#### Current Version:
v2.33.0

**Comment by mitzimorris** [comment]
further digging - `[ ... \]` is latex vs `$$ ... $$` tex.
online discussion suggests that `\begin{equation*}` is equivalent to `\[` and this seems to work in quarto.

**Comment by WardBrian** [comment]
Getting rid of as many calls to R as possible would also be nice - especially around table formatting. 

We can look into replacements for the `since(...)` helper in the functions reference as well

**Comment by mitzimorris** [comment]
it's not clear to me whether or not quarto comes with R baked in, or whether it only uses R script to process Rmd.   to be investigated at some future point.

**Comment by WardBrian** [comment]
I don't believe it does - at least, on my machine, I get an error if I don't have R already loaded in my environment
