### ISSUE TITLE
Add a section on numerical reproducibility

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/docs#69]
#### Summary:
As mentioned in the Discourse thread [here](https://discourse.mc-stan.org/t/gpu-glms-float-or-double/9484/37) we should add a section on  determinism in scientific computing (numerical reproducibility).

#### Description:
Below is my draft for this section. Once the text is approved I can make a PR.

Numerical reproducibility is the problem of getting the exact same numerical result in all runs of the same algorithm. In the context of Stan this would mean that a model with the same seed and input data produces the exact same samples in the same order every time we run it.

There are two main issues that prevent numerical reproducibility: 

a) Differences in implementation of floating point arithmetic

Most current processing units, CPU and GPU, follow the same variant of the IEEE754 standard. However, the standard allows for different implementations of rounding that can lead to numerical differences. This makes it more difficult to achieve numerical reproducibility across different systems.

b) Non-determinism of the order of arithmetic operations

A sequential algorithm with the same random seed will always perform all arithmetic operations in the exact same order. Rounding will always occur at the exact same points. However, if the algorithm includes parallel reductions, the order of operations is no longer deterministic. Rounding may occur at different points and lead to numerical differences. This goes for simple cases of 4 threads performing a `reduce_sum` on a vector as well as GPU functions running on thousands of threads.

#### Additional Information:
/

#### Current Version:
v2.18.0

**Comment by mitzimorris** [comment]
probably should go into User's Guide Floating Point chapter -

file: src/stan-users-guide/floating-point.Rmd

**Comment by mitzimorris** [comment]
@bob-carpenter - please take a look

**Comment by rok-cesnovar** [comment]
I agree. Since some of what is written in the above paragraphs is already there I will re-do this a bit.

**Comment by bob-carpenter** [comment]
There's also a full chapter on reproducibility already in the reference manual:

https://mc-stan.org/docs/2_18/reference-manual/reproducibility-chapter.html

**Comment by mitzimorris** [comment]
@rok-cesnovar OK to close?
