### ISSUE TITLE
CDF definition is wrong for discrete distributions

### ISSUE THREAD

**Issue by nhuurre** [stan-dev/docs#71]
#### Description:
Stan Functions Reference section 10.7 Cumulative Distribution Functions says the CDF function is F(y) = Pr[X<y] but this wrong. The correct definition is F(y) = Pr[X<=y], i.e. an inclusive rather than exclusive bound. This distinction is important for discrete distributions even though it makes no difference for continuous distributions like the normal distribution given as an example in the text. It would be a good idea to also have a discrete example, such as binomial.

#### Additional Information:
binomial_cdf(0,3,0.5) = 0.125
binomial_cdf(1,3,0.5) = 0.5
binomial_cdf(2,3,0.5) = 0.875
binomial_cdf(3,3,0.5) = 1.0

#### Current Version:
v2.19.0

**Comment by bob-carpenter** [comment]
Thanks.  Definitely a bug.  I agree we should include discrete examples.  And make sure the CCDF is also right (being the complement, it switches `<=` for `>`). 

I'm going to put a link from our doc issues page to make sure this gets fixed.

**Comment by jgabry** [comment]
Thanks @nhuurre for reporting and to @mcol for fixing!
