### ISSUE TITLE
Problem searching the functions reference

### ISSUE THREAD

**Issue by martinmodrak** [stan-dev/docs#740]
#### Summary:
When using the built-in search function from within functions reference, I only see search results from the User's guide, but not results from functions reference.

#### Description:
1) Open https://mc-stan.org/docs/functions-reference/
2) Start searching using the search icon
3) Enter `diag_pre_multiply`
4) The page https://mc-stan.org/docs/functions-reference/matrix_operations.html does not appear in the search results

![obrazek](https://github.com/stan-dev/docs/assets/9483603/8d55c012-dace-4835-8e4e-58f2f93b68df)

The new look of the docs is great, so hope those teething issues get ironed out soon and thanks for all the work!

#### Additional Information:
Windows 10, Firefox 123

#### Current Version:
v2.34.1

**Comment by mitzimorris** [comment]
-  the built-in search is slow - it can take a while to find everything - we're looking into using Algolia search instead of quarto's hacky one.

-  for this particular search, we just added an online index to the functions reference

**Comment by WardBrian** [comment]
This is an issue with the quarto default search which has an "optimization" that leads to results being missing: https://github.com/quarto-dev/quarto-cli/issues/8986

It unfortunately seems to be much worse in Firefox than other browsers, which is why I've also been working on it.

**Comment by WardBrian** [comment]
(A very silly workaround is because this bug comes from an optimization around common prefixes, if you want to search for `diag_pre_multiply`, you can search for `xdiag_pre_multiply` and then delete the `x`, re-setting the prefix matching. Obviously this isn't a solution, but in the mean time it is what I have been doing on Firefox)
