### ISSUE TITLE
Feature request: provide function reference search url

### ISSUE THREAD

**Issue by botanize** [stan-dev/docs#76]
#### Summary:
I think it would be great to lookup function documentation by using a search URL template similar to this: https://developer.apple.com/search/?q=switch&amp;type=Reference
Where you simply replace `_SYMBOLNAME_` with the name of the function. Though I admit that is not the greatest example.

This would be helpful for text-editors that support reference lookups, like BBEdit.
https://www.barebones.com/support/develop/clm.html#BBLMReferenceSearchURLTemplate

**Comment by bob-carpenter** [comment]
Sounds like a good idea.  We currently serve our docs through GitHub and they use some fancy built-in search if you pull up the search box.  Could that be rigged to do what you'd like?  I'm not sure how to give it an external URL.

**Comment by botanize** [comment]
I took a look at the bookdown/gitbook [HTML documentation](https://mc-stan.org/docs/2_20/functions-reference/index.html), it has search functionality, but that is exclusively through javascript, and can't be accessed through the URL.

I tried using github search to find the correct [function reference Rmd](https://github.com/stan-dev/docs/tree/master/src/functions-reference) file or the built [HTML](https://github.com/stan-dev/docs/tree/master/docs/functions-reference) version. Seems like it can find a file in the right format, but it doesn't serve those files directly, so the user would be presented with an unrendered HTML document at best. 

It looks like `readthedocs` provides this functionality, for example [https://pystan.readthedocs.io/en/latest/search.html?q=stanc](https://pystan.readthedocs.io/en/latest/search.html?q=stanc). But I don't know what it would take to convert the function reference documentation to the necessary format. I'd consider doing the conversion myself, but I don't want to have to maintain a separate documentation.

I'll be the first to admit there probably isn't a straightforward solution. But I thought it would be something to keep in mind.

**Comment by bob-carpenter** [comment]
@botanzie --- thanks for looking into this.  

@mitzimorris added search to https://mc-stan.org, but that's not restricted to function doc and also returns HTML rather than something structured.

We have standoff csv-like lists of functions that I believe RStudio is using, but there's no server backing them up.  @bgoodri is the one who deals with those.

Sorry this is so convoluted---our team's very distributed across interfaces/platforms, etc.

**Comment by bgoodri** [comment]
We cache a lookup table in RStan, but that is not too important to the idea
of enhancing the website.

**Comment by bob-carpenter** [comment]
I believe the request is for a function search web service that editors could use, not something user facing.

**Comment by mitzimorris** [comment]
if you want to plug in lookup to your editor,  there are html comments in the pages for the functions reference docs for the function signatures,  e.g., the html page for the wishart contains the following:
```
wishart-distribution.html
589:<!-- real; wishart ~; -->
594:<!-- real; wishart_lpdf; (matrix W | real nu, matrix Sigma); -->
600:<!-- matrix; wishart_rng; (real nu, matrix Sigma); -->
```

if you check out the repo  https://github.com/stan-dev/docs,  the HTML is in directory `docs/<X_Y>/functions-reference` (where X_Y are latest major, minor release, e.g. 2_20).

we have a set of redirect pages, so you can create entries for `wishart (sampling)`, `wishart_lpdf`, and `wishart_rng`  all of which go to:

https://mc-stan.org/docs/functions-reference/wishart-distribution.html

by virtue of redirects, this will take you to latest version.

is this what you're looking for?

if so, you could:

1. checkout docs repo, cd directory `docs/2_20/functions-reference`
2. use `grep`, e.g. `grep '<!--' *.html`
3. create whatever table your editor uses

**Comment by mitzimorris** [comment]
docs repo now has Python program `extract_function_sigs.py` which can be used to generate a functions listing.
