### ISSUE TITLE
Typing and scope of loop variables

### ISSUE THREAD

**Issue by feuerbach** [stan-dev/docs#77]
#### Summary:

The section [Loop Variable Typing and Scope](https://github.com/stan-dev/docs/blob/master/src/reference-manual/statements.Rmd#L768-L778) does not explain either the typing or the scope of loop variables.

#### Description:

I'd expect the section to document:

1. The typing (loop variables have type `int`), as explained in the [Expressions](https://github.com/stan-dev/docs/blob/master/src/reference-manual/expressions.Rmd#L1043-L1044) chapter.
2. Scope — presumably loop variables only scope over the body of the loop.

**Comment by jgabry** [comment]
Thanks @feuerbach for reporting this and to @mcol for fixing (PR #79)!
