### ISSUE TITLE
GP Covariance Functions: minor tweak

### ISSUE THREAD

**Issue by joshuaalley** [stan-dev/docs#809]
#### Summary:
This is really small, but I think that the [documentation for Gaussian Processes](https://mc-stan.org/docs/stan-users-guide/gaussian-processes.html) uses the old cov_exp_quad, instead of gp_exp_quad_cov and the like. 

#### Description:
For instance, the kernel is written as:   matrix[N, N] K = cov_exp_quad(x, alpha, rho);

In the [STAN Matrix Operations Docs](https://mc-stan.org/docs/functions-reference/matrix_operations.html#gaussian-process-covariance-functions), the kernels are gp_exp_quad_cov. 

#### Additional Information:
Using cov_exp_quad now throws compilation errors on cmdstan, so people who follow the user guide on may have some problems. 

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
Thanks for submitting---we will fix.
