### ISSUE TITLE
Cmdstan install documentation refers to `ls` instead of `wc`

### ISSUE THREAD

**Issue by jannepeltola** [stan-dev/docs#812]
#### Summary:
The Cmdstan install guide (`src/cmdstan-guide/installation.qmd`) asks the user to count lines in a text file using `ls` on line 231. The command should probably be `wc`.

#### Description:

The Cmdstan install guide (`src/cmdstan-guide/installation.qmd`) asks the user to count lines in a text file using `ls` on line 231. The command should probably be `wc`. Seems like a plain typo.

This is my first contribution to Stan and I’m trying to follow the developer guidelines to my best.

PS. Inspired by Mitzi’s talk at Stancon!

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
fixed with #813
