### ISSUE TITLE
Description of `log_diff_exp` potentially misleading

### ISSUE THREAD

**Issue by dylanhmorris** [stan-dev/docs#814]
### Summary:
The [documentation for `log_diff_exp`](https://mc-stan.org/docs/functions-reference/real-valued_basic_functions.html#composed-functions) states:

> $$
> \mathrm{log\\_diff\\_exp}(x, y) = \begin{cases}
> \log(\exp(x) - \exp(y)) & \mathrm{if \\;} x > y \\
> \mathrm{NaN} & \mathrm{otherwise}
> \end{cases}
> $$

but `log_diff_exp` returns `-Inf`, not `NaN`, for `x == y`, provided `x, y < Inf` (including for `x == y == -Inf`).

#### Documentation quarto source:

https://github.com/stan-dev/docs/blob/b645f4db66ad80d8aae97fa094d253f789265a2f/src/functions-reference/real-valued_basic_functions.qmd#L1600-L1605

#### Relevant lines of `log_diff_exp` source code:

https://github.com/stan-dev/math/blob/9b1f08be7e76c6468fc2fcf2f75d641a619ae349/stan/math/prim/fun/log_diff_exp.hpp#L51-L56

#### Reproducible example in R with `cmdstanr`:

```R
library(cmdstanr)

reprex <- "generated quantities {

   real log_diff_equal = log_diff_exp(-5, -5);
   real log_diff_neg_infs = log_diff_exp(negative_infinity(),
                                         negative_infinity());
   real log_diff_pos_infs = log_diff_exp(positive_infinity(),
                                         positive_infinity());
   real log_diff_greater = log_diff_exp(-5, -4.9999);

}
"

mod <- cmdstan_model(write_stan_file(reprex))
samp <- mod$sample(fixed_param=TRUE, iter_sampling=1, chains=1)

print(samp)
```

This yields:
```R
 variable        mean   median sd mad   q5  q95 rhat ess_bulk ess_tail
 log_diff_equal    -Inf   -Inf NA  NA -Inf -Inf   NA       NA       NA
 log_diff_neg_infs -Inf   -Inf NA  NA -Inf -Inf   NA       NA       NA
 log_diff_pos_infs  NaN     NA NA  NA   NA   NA   NA       NA       NA
 log_diff_greater   NaN     NA NA  NA   NA   NA   NA       NA       NA
```

### Version information
Documentation version 2.35 on https://mc-stan.org/
Example produced with `cmdstan` v.2.35.0 and `cmdstanr` v.0.8.1.9000

**Comment by dylanhmorris** [comment]
Happy to make a PR myself if it would be helpful or to leave it to the main devs if that's easier. Let me know.

**Comment by bob-carpenter** [comment]
Sure, if you can make a PR to fix it, that'd be great.  I'll be able to review it quickly.

**Comment by dylanhmorris** [comment]
Opened #815.
