### ISSUE TITLE
Wrong version numbers in "Available since" in the functions reference

### ISSUE THREAD

**Issue by jgabry** [stan-dev/docs#816]
#### Summary:

The function reference has "Available since" and then the version number, which is great, but some of the version numbers seem wrong. For example, version 2.5 appears in multiple places, but Stan is only at 2.35. Here's one such case: 

https://github.com/stan-dev/docs/blob/ba8c1c5c1108d8867d911768f347edf441f58071/src/functions-reference/matrix_operations.qmd#L15

**Comment by WardBrian** [comment]
Stan 2.5 was released in 2014: https://github.com/stan-dev/stan/releases/tag/v2.5.0

Stan 2.50 is a hypothetical unreleased version which is distinct from this. Arguably the older version could have been called 2.05, but it wasn't at the time

**Comment by bob-carpenter** [comment]
We use what is known as "semantic versioning" and the convention is to read these as a sequence of natural numbers, not fractions.  So `2.5` is correct as written.  You can get more background here:

https://en.wikipedia.org/wiki/Software_versioning

In particular, this:

> Most [free and open-source software](https://en.wikipedia.org/wiki/Free_and_open-source_software) packages, including [MediaWiki](https://en.wikipedia.org/wiki/MediaWiki), treat versions as a series of individual numbers, separated by periods, with a progression such as 1.7.0, 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.11.0, 1.11.1, 1.11.2, and so on.

The page discusses projects that do treat them like fractions, too.

> some software packages identify releases by decimal numbers: 1.7, 1.8, 1.81, 1.82, 1.9, etc. Decimal versions were common in the 1980s

I call such schemes "Xeno versioning".  Those usually start with "0.", following Google's practice of avoiding 1.0 releases.

**Comment by jgabry** [comment]
Oops, yeah you’re absolutely right!  And I even knew that and totally
forgot!
