### ISSUE TITLE
General Discussion of Priors Deadends

### ISSUE THREAD

**Issue by nathan-zymergen** [stan-dev/docs#83]
#### Summary:
There is supposedly a link to a "General Discussion of Priors" in section 1.3 of the Stan 1.20 manual. It currently deadends, though. I'm relatively new to Bayesian modeling, so I would love to know your thoughts on these. :)

#### Current Version:
v2.20.0

**Comment by andrewgelman** [comment]
Here:  https://github.com/stan-dev/stan/wiki/Prior-Choice-Recommendations
