### ISSUE TITLE
Document new diagnostics

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/docs#835]
#### Summary:
The pages at https://github.com/stan-dev/docs/blob/master/src/cmdstan-guide/stansummary.qmd and https://github.com/stan-dev/docs/tree/master/src/reference-manual/analysis.qmd need to be updated following @mitzimorris' work on the "new" Rhat/ESS from https://arxiv.org/abs/1903.08008 in stansummary.

See
https://github.com/stan-dev/stan/pull/3313
https://github.com/stan-dev/cmdstan/pull/1301

**Comment by WardBrian** [comment]
@avehtari would you have the time to take a look at these?

**Comment by avehtari** [comment]
I'll check these, and hopefully have time before the next release
