### ISSUE TITLE
Remove work files from repository

### ISSUE THREAD

**Issue by mcol** [stan-dev/docs#87]
#### Summary:
The repository contains temporary log files and cache directories that can cause build issues.

#### Description:
Commit 2838be3 (by @serban-nicusor-toptal) added a number of files that aren't worth tracking. In particular, the presence of the `stan-users-guide/_bookdown_files/_main_cache` directory doesn't allow building the html version of the user's guide, as some paths are hardcoded in the cached files:

```
> python build.py 2 21 stan-users-guide html

<cut>
output file: _main.knit.md

List of 10
 $ name      : chr "kePrint"
 $ version   : chr "0.0.1"
 $ src       :List of 1
  ..$ file: chr "C:/Users/Nick/R/win-library/3.6/kableExtra/kePrint-0.0.1"
 $ meta      : NULL
 $ script    : chr "kePrint.js"
 $ stylesheet: NULL
 $ head      : NULL
 $ attachment: NULL
 $ package   : NULL
 $ all_files : logi TRUE
 - attr(*, "class")= chr "html_dependency"
Error: path for html_dependency not found: C:/Users/Nick/R/win-library/3.6/kableExtra/kePrint-0.0.1
Execution halted
```

**Comment by serban-nicusor-toptal** [comment]
Didn't see that, thank you!
