### ISSUE TITLE
strip out extract 1 iteration

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#9]
#### Summary:
Please provide a short couple sentence summary.

#### Description:
Describe the issue as clearly as possible.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by mitzimorris** [comment]
not sure what this refers to - closing

**Comment by bob-carpenter** [comment]
There's an extract_one_iteration function or something like that, which is being used in the R.  It's in the before-chapter.R, I think.  Users are reporting they are trying to follow the R as rendered in the HTML and this function isn't defined.

So we either need to make the HTML actually runnable or get rid of it.  Or provide instructions on how to install the "before-chapter" code.

**Comment by mitzimorris** [comment]
reopening - will add code and explanation to fake-data-simulation chapper.

**Comment by mitzimorris** [comment]
closing again - WIP "bayes-workflow-book" has its own repo
