### ISSUE TITLE
HMC formula corrections for user's guide

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/docs#91]
#### Summary:

@andrewgelman [blogged](https://statmodeling.stat.columbia.edu/2019/09/29/convergence-diagnostics-for-markov-chain-simulation/#comment-1132559) a bug report from Pierre Jacob:

> if rho is Normal(0, Sigma), then the second step of the integrator should read theta <- theta + epsilon Sigma^{-1} rho. Also, I believe that "mass matrix" usually refers to the covariance of the momentum variable in the literature, e.g. "M" in "MCMC using Hamiltonian dynamics" by Radford Neal, which is contrary to what you write in the section "Auxiliary Momentum Variable".

#### Description:

Review and fix.

#### Current Version:
v2.18.0

**Comment by mcol** [comment]
This was fixed by #100 (and #109).
