### ISSUE TITLE
Sign error in "Ability and Difficulty in IRT Models“ | Stan users guide 2.20

### ISSUE THREAD

**Issue by asperamanka** [stan-dev/docs#96]
#### Summary:
There is a sign error in the Stan users guide 2.20 in chapter "problematic posteriors" in section "Ability and Difficulty in IRT Models“ - in the 2nd equation in this section and in its description in the text.

#### Description:
The text says
> For any constant c, the probability of y is unchanged by adding a constant c to all the abilities and subtracting it from all the difficulties, i.e., p(y|\alpha,\beta) = p(y|\alpha + c, \beta − c).

#### Solution
A corrected version could be:
> Since the probability of y depends only on the difference of the ability and difficulty, it is unchanged by adding (or subtracting) a constant c to all the abilities and difficulties, i.e., p(y|\alpha,\beta) = p(y|\alpha + c, \beta + c).

**Comment by mcol** [comment]
I think you are correct, I'll post a patch to address this.
